export const Day1Word = [
  {
    Word: "Hello",
    Word_Meaning: "안녕하세요",
    English_Sentence: "Hello, how are you?",
    English_Sentence_Mean: "안녕하세요, 어떻게 지내세요?",
  },
  {
    Word: "Goodbye",
    Word_Meaning: "안녕히 가세요/안녕",
    English_Sentence: "It's time to say goodbye.",
    English_Sentence_Mean: "이제 안녕히 가야 할 시간이에요.",
  },
  {
    Word: "Please",
    Word_Meaning: "제발",
    English_Sentence: "Can you help me, please?",
    English_Sentence_Mean: "도와주세요, 제발.",
  },
  {
    Word: "Thank you",
    Word_Meaning: "감사합니다",
    English_Sentence: "Thank you for your kind words.",
    English_Sentence_Mean: "친절한 말에 감사합니다.",
  },
  {
    Word: "Yes",
    Word_Meaning: "네",
    English_Sentence: "Yes, I can do that.",
    English_Sentence_Mean: "네, 그것을 할 수 있어요.",
  },
  {
    Word: "No",
    Word_Meaning: "아니요",
    English_Sentence: "No, I haven't seen it.",
    English_Sentence_Mean: "아니요, 제가 보지 못했어요.",
  },
  {
    Word: "Excuse me",
    Word_Meaning: "실례합니다",
    English_Sentence: "Excuse me, do you have a minute?",
    English_Sentence_Mean: "실례합니다, 시간 좀 괜찮으세요?",
  },
  {
    Word: "Sorry",
    Word_Meaning: "죄송합니다",
    English_Sentence: "I'm sorry for the mistake.",
    English_Sentence_Mean: "그 실수에 대해 죄송합니다.",
  },
  {
    Word: "What",
    Word_Meaning: "뭐/무엇",
    English_Sentence: "What is your name?",
    English_Sentence_Mean: "당신의 이름은 무엇인가요?",
  },
  {
    Word: "Where",
    Word_Meaning: "어디",
    English_Sentence: "Where is the nearest cafe?",
    English_Sentence_Mean: "가장 가까운 카페는 어디에요?",
  },
  {
    Word: "When",
    Word_Meaning: "언제",
    English_Sentence: "When will the event start?",
    English_Sentence_Mean: "이벤트는 언제 시작되나요?",
  },
  {
    Word: "Why",
    Word_Meaning: "왜",
    English_Sentence: "Why did you choose this book?",
    English_Sentence_Mean: "왜 이 책을 선택했나요?",
  },
  {
    Word: "How",
    Word_Meaning: "어떻게",
    English_Sentence: "How do you solve this problem?",
    English_Sentence_Mean: "이 문제를 어떻게 해결하나요?",
  },
  {
    Word: "I",
    Word_Meaning: "나/저",
    English_Sentence: "I love to travel.",
    English_Sentence_Mean: "나는 여행을 좋아해요.",
  },
  {
    Word: "You",
    Word_Meaning: "너/당신",
    English_Sentence: "Can you pass me the salt?",
    English_Sentence_Mean: "소금 좀 내려 주시겠어요?",
  },
  {
    Word: "He",
    Word_Meaning: "그 (informal)/그분 (formal)",
    English_Sentence: "He is my brother.",
    English_Sentence_Mean: "그는 제 동생이에요.",
  },
  {
    Word: "She",
    Word_Meaning: "그녀 (formal)",
    English_Sentence: "She works in a hospital.",
    English_Sentence_Mean: "그녀는 병원에서 일해요.",
  },
  {
    Word: "It",
    Word_Meaning: "그것",
    English_Sentence: "It is a beautiful day.",
    English_Sentence_Mean: "오늘은 아름다운 날씨에요.",
  },
  {
    Word: "We",
    Word_Meaning: "우리",
    English_Sentence: "We are going on a trip.",
    English_Sentence_Mean: "우리는 여행을 갑니다.",
  },
  {
    Word: "They",
    Word_Meaning: "그들",
    English_Sentence: "They are my friends.",
    English_Sentence_Mean: "그들은 제 친구들이에요.",
  },
  {
    Word: "This",
    Word_Meaning: "이/이것",
    English_Sentence: "This is my book.",
    English_Sentence_Mean: "이것은 제 책이에요.",
  },
  {
    Word: "That",
    Word_Meaning: "저/저것",
    English_Sentence: "That is a nice car.",
    English_Sentence_Mean: "저것은 좋은 차에요.",
  },
  {
    Word: "Here",
    Word_Meaning: "여기",
    English_Sentence: "Come here, please.",
    English_Sentence_Mean: "여기로 와 주세요.",
  },
  {
    Word: "There",
    Word_Meaning: "거기",
    English_Sentence: "The store is over there.",
    English_Sentence_Mean: "가게는 저기에 있어요.",
  },
  {
    Word: "Who",
    Word_Meaning: "누구",
    English_Sentence: "Who is that person?",
    English_Sentence_Mean: "저 사람은 누구에요?",
  },
  {
    Word: "What",
    Word_Meaning: "무엇",
    English_Sentence: "What is your favorite color?",
    English_Sentence_Mean: "당신의 좋아하는 색깔은 무엇인가요?",
  },
  {
    Word: "Which",
    Word_Meaning: "어느 것",
    English_Sentence: "Which one do you prefer?",
    English_Sentence_Mean: "어느 것이 더 선호하시나요?",
  },
  {
    Word: "Other",
    Word_Meaning: "다른",
    English_Sentence: "I'll take the other one.",
    English_Sentence_Mean: "나는 다른 것을 가져갈게요.",
  },
  {
    Word: "Some",
    Word_Meaning: "일부/얼마",
    English_Sentence: "I bought some fruits.",
    English_Sentence_Mean: "일부 과일을 샀어요.",
  },
  {
    Word: "Few",
    Word_Meaning: "조금",
    English_Sentence: "There are only a few left.",
    English_Sentence_Mean: "조금만 남았어요.",
  },
  {
    Word: "Many",
    Word_Meaning: "많은",
    English_Sentence: "There are many books on the shelf.",
    English_Sentence_Mean: "책장에 많은 책이 있어요.",
  },
  {
    Word: "Much",
    Word_Meaning: "많이",
    English_Sentence: "I don't have much time.",
    English_Sentence_Mean: "많은 시간이 없어요.",
  },
  {
    Word: "Little",
    Word_Meaning: "적은",
    English_Sentence: "She has a little money.",
    English_Sentence_Mean: "그녀는 조금 돈이 있어요.",
  },
  {
    Word: "Big",
    Word_Meaning: "큰",
    English_Sentence: "It's a big house.",
    English_Sentence_Mean: "큰 집이에요.",
  },
  {
    Word: "Small",
    Word_Meaning: "작은",
    English_Sentence: "She has a small car.",
    English_Sentence_Mean: "그녀는 작은 차를 가지고 있어요.",
  },
  {
    Word: "Good",
    Word_Meaning: "좋은",
    English_Sentence: "This is a good movie.",
    English_Sentence_Mean: "이것은 좋은 영화에요.",
  },
  {
    Word: "Bad",
    Word_Meaning: "나쁜",
    English_Sentence: "Smoking is bad for your health.",
    English_Sentence_Mean: "흡연은 건강에 나쁘다.",
  },
  {
    Word: "Happy",
    Word_Meaning: "행복한",
    English_Sentence: "I am happy to see you.",
    English_Sentence_Mean: "당신을 만나서 행복해요.",
  },
  {
    Word: "Sad",
    Word_Meaning: "슬픈",
    English_Sentence: "She looks sad today.",
    English_Sentence_Mean: "그녀가 오늘은 슬플 것 같아요.",
  },
  {
    Word: "Angry",
    Word_Meaning: "화난",
    English_Sentence: "He is angry about the decision.",
    English_Sentence_Mean: "그는 그 결정에 화가 나 있어요.",
  },
  {
    Word: "Love",
    Word_Meaning: "사랑",
    English_Sentence: "They are in love.",
    English_Sentence_Mean: "그들은 사랑에 빠져 있어요.",
  },
  {
    Word: "Hate",
    Word_Meaning: "미움",
    English_Sentence: "I don't hate anyone.",
    English_Sentence_Mean: "나는 아무도 미워하지 않아요.",
  },
  {
    Word: "Friend",
    Word_Meaning: "친구",
    English_Sentence: "She is my best friend.",
    English_Sentence_Mean: "그녀는 제 가장 친한 친구에요.",
  },
  {
    Word: "Enemy",
    Word_Meaning: "적",
    English_Sentence: "He considered her his enemy.",
    English_Sentence_Mean: "그는 그녀를 자신의 적으로 여겼어요.",
  },
  {
    Word: "Family",
    Word_Meaning: "가족",
    English_Sentence: "I love spending time with my family.",
    English_Sentence_Mean: "나는 가족과 시간을 보는 것을 좋아해요.",
  },
  {
    Word: "Mother",
    Word_Meaning: "어머니",
    English_Sentence: "My mother is a great cook.",
    English_Sentence_Mean: "내 어머니는 훌륭한 요리사에요.",
  },
  {
    Word: "Father",
    Word_Meaning: "아버지",
    English_Sentence: "My father loves gardening.",
    English_Sentence_Mean: "내 아버지는 가드닝을 좋아해요.",
  },
  {
    Word: "Brother",
    Word_Meaning: "형제",
    English_Sentence: "My brother is studying abroad.",
    English_Sentence_Mean: "내 동생은 해외에서 공부하고 있어요.",
  },
  {
    Word: "Sister",
    Word_Meaning: "자매",
    English_Sentence: "My sister is a talented musician.",
    English_Sentence_Mean: "내 누나는 재능 있는 음악가에요.",
  },
  {
    Word: "Son",
    Word_Meaning: "아들",
    English_Sentence: "My son wants to be an astronaut.",
    English_Sentence_Mean: "내 아들은 우주비행사가 되고 싶어해요.",
  },
];
