export const Day2Word = [
  {
    Word: "Husband",
    Word_Meaning: "남편",
    English_Sentence: "My husband is a doctor.",
    English_Sentence_Mean: "내 남편은 의사에요.",
  },
  {
    Word: "Wife",
    Word_Meaning: "아내",
    English_Sentence: "His wife is an artist.",
    English_Sentence_Mean: "그의 아내는 예술가에요.",
  },
  {
    Word: "Boyfriend",
    Word_Meaning: "남자 친구",
    English_Sentence: "My boyfriend gave me flowers.",
    English_Sentence_Mean: "내 남자 친구가 나에게 꽃을 선물했어요.",
  },
  {
    Word: "Girlfriend",
    Word_Meaning: "여자 친구",
    English_Sentence: "She is my girlfriend since college.",
    English_Sentence_Mean: "대학 시절부터 그녀는 나의 여자 친구에요.",
  },
  {
    Word: "Friend",
    Word_Meaning: "친구",
    English_Sentence: "I met a friend at the park.",
    English_Sentence_Mean: "나는 공원에서 친구를 만났어요.",
  },
  {
    Word: "Foe",
    Word_Meaning: "적",
    English_Sentence: "He considered him a lifelong foe.",
    English_Sentence_Mean: "그는 그를 평생의 적으로 여겼어요.",
  },
  {
    Word: "Eat",
    Word_Meaning: "먹다",
    English_Sentence: "Let's eat dinner together.",
    English_Sentence_Mean: "우리 함께 저녁을 먹자.",
  },
  {
    Word: "Drink",
    Word_Meaning: "마시다",
    English_Sentence: "I like to drink coffee in the morning.",
    English_Sentence_Mean: "나는 아침에 커피를 마시는 것을 좋아해.",
  },
  {
    Word: "Sleep",
    Word_Meaning: "자다",
    English_Sentence: "I need to sleep early tonight.",
    English_Sentence_Mean: "오늘 밤에 일찍 자야 돼.",
  },
  {
    Word: "Wake",
    Word_Meaning: "깨다",
    English_Sentence: "I usually wake up at 7 AM.",
    English_Sentence_Mean: "나는 보통 아침 7시에 일어나.",
  },
  {
    Word: "Go",
    Word_Meaning: "가다",
    English_Sentence: "Let's go to the beach this weekend.",
    English_Sentence_Mean: "이번 주말에 해변에 가자.",
  },
  {
    Word: "Come",
    Word_Meaning: "오다",
    English_Sentence: "Can you come to my party?",
    English_Sentence_Mean: "내 파티에 올 수 있을까요?",
  },
  {
    Word: "Stop",
    Word_Meaning: "멈추다",
    English_Sentence: "Please stop talking and listen.",
    English_Sentence_Mean: "말을 멈추고 들어주세요.",
  },
  {
    Word: "Start",
    Word_Meaning: "시작하다",
    English_Sentence: "Let's start the project tomorrow.",
    English_Sentence_Mean: "우리 내일 프로젝트를 시작하자.",
  },
  {
    Word: "Finish",
    Word_Meaning: "끝내다",
    English_Sentence: "I will finish the report by tomorrow.",
    English_Sentence_Mean: "나는 내일까지 보고서를 끝낼 거야.",
  },
  {
    Word: "Work",
    Word_Meaning: "일하다",
    English_Sentence: "She works in a software company.",
    English_Sentence_Mean: "그녀는 소프트웨어 회사에서 일해.",
  },
  {
    Word: "Play",
    Word_Meaning: "놀다",
    English_Sentence: "Children love to play in the park.",
    English_Sentence_Mean: "어린이들은 공원에서 놀기를 좋아해요.",
  },
  {
    Word: "Study",
    Word_Meaning: "공부하다",
    English_Sentence: "I need to study for the exam.",
    English_Sentence_Mean: "시험 공부를 해야 해.",
  },
  {
    Word: "Learn",
    Word_Meaning: "배우다",
    English_Sentence: "I want to learn how to play the piano.",
    English_Sentence_Mean: "나는 피아노를 어떻게 칠지 배우고 싶어.",
  },
  {
    Word: "Teach",
    Word_Meaning: "가르치다",
    English_Sentence: "Can you teach me how to dance?",
    English_Sentence_Mean: "나에게 춤을 가르쳐 줄 수 있을까요?",
  },
  {
    Word: "Read",
    Word_Meaning: "읽다",
    English_Sentence: "I love to read novels before bed.",
    English_Sentence_Mean: "나는 자기 전에 소설을 읽는 것을 좋아해.",
  },
  {
    Word: "Write",
    Word_Meaning: "쓰다",
    English_Sentence: "She likes to write poetry.",
    English_Sentence_Mean: "그녀는 시를 쓰는 것을 좋아해.",
  },
  {
    Word: "Speak",
    Word_Meaning: "말하다",
    English_Sentence: "Can you speak Spanish?",
    English_Sentence_Mean: "스페인어 할 수 있을까요?",
  },
  {
    Word: "Listen",
    Word_Meaning: "듣다",
    English_Sentence: "Listen to the music and relax.",
    English_Sentence_Mean: "음악을 듣고 편안해져.",
  },
  {
    Word: "Watch",
    Word_Meaning: "보다",
    English_Sentence: "Let's watch a movie tonight.",
    English_Sentence_Mean: "오늘 밤에 영화를 보자.",
  },
  {
    Word: "See",
    Word_Meaning: "보다",
    English_Sentence: "I can see the mountains from here.",
    English_Sentence_Mean: "여기서 산을 볼 수 있어.",
  },
  {
    Word: "Hear",
    Word_Meaning: "듣다",
    English_Sentence: "I can hear the birds singing.",
    English_Sentence_Mean: "새들의 노래가 들려.",
  },
  {
    Word: "Touch",
    Word_Meaning: "만지다",
    English_Sentence: "Please don't touch the artwork.",
    English_Sentence_Mean: "작품에 손 대지 마세요.",
  },
  {
    Word: "Smell",
    Word_Meaning: "냄새 맡다",
    English_Sentence: "I love the smell of fresh bread.",
    English_Sentence_Mean: "신선한 빵의 향기를 좋아해.",
  },
  {
    Word: "Taste",
    Word_Meaning: "맛을 보다",
    English_Sentence: "The soup has a rich taste.",
    English_Sentence_Mean: "이 수프는 풍부한 맛이 나.",
  },
  {
    Word: "Feel",
    Word_Meaning: "느끼다",
    English_Sentence: "I can feel the warmth of the sun.",
    English_Sentence_Mean: "나는 햇볕의 따뜻함을 느낄 수 있어.",
  },
  {
    Word: "Hot",
    Word_Meaning: "뜨거운",
    English_Sentence: "The tea is too hot to drink.",
    English_Sentence_Mean: "차가 마시기에 너무 뜨거워.",
  },
  {
    Word: "Cold",
    Word_Meaning: "추운",
    English_Sentence: "It's so cold outside.",
    English_Sentence_Mean: "밖이 너무 추워.",
  },
  {
    Word: "Warm",
    Word_Meaning: "따뜻한",
    English_Sentence: "Wrap yourself in a warm blanket.",
    English_Sentence_Mean: "따뜻한 담요에 싸여.",
  },
  {
    Word: "Cool",
    Word_Meaning: "시원한",
    English_Sentence: "The breeze feels cool on a hot day.",
    English_Sentence_Mean: "더운 날씨에는 바람이 시원해 느껴져.",
  },
  {
    Word: "Beautiful",
    Word_Meaning: "아름다운",
    English_Sentence: "The sunset is so beautiful.",
    English_Sentence_Mean: "일몰이 정말 아름답다.",
  },
  {
    Word: "Ugly",
    Word_Meaning: "추한",
    English_Sentence: "Beauty is in the eye of the beholder.",
    English_Sentence_Mean: "아름다움은 감상하는 이의 눈에 달려 있다.",
  },
  {
    Word: "Clean",
    Word_Meaning: "깨끗한",
    English_Sentence: "The room is clean and tidy.",
    English_Sentence_Mean: "방이 깨끗하고 정돈되어 있다.",
  },
  {
    Word: "Dirty",
    Word_Meaning: "더러운",
    English_Sentence: "Please don't enter with dirty shoes.",
    English_Sentence_Mean: "더러운 신발로 들어가지 마세요.",
  },
  {
    Word: "Fast",
    Word_Meaning: "빠른",
    English_Sentence: "He is a fast runner.",
    English_Sentence_Mean: "그는 빠른 달리기 선수에요.",
  },
  {
    Word: "Slow",
    Word_Meaning: "느린",
    English_Sentence: "The turtle moves slow.",
    English_Sentence_Mean: "거북이는 느리게 움직여.",
  },
  {
    Word: "Old",
    Word_Meaning: "늙은",
    English_Sentence: "The house looks old but charming.",
    English_Sentence_Mean: "집은 낡아 보이지만 매력적이에요.",
  },
  {
    Word: "New",
    Word_Meaning: "새로운",
    English_Sentence: "I got a new phone yesterday.",
    English_Sentence_Mean: "나는 어제 새로운 핸드폰을 샀어.",
  },
  {
    Word: "Young",
    Word_Meaning: "젊은",
    English_Sentence: "She is a talented young artist.",
    English_Sentence_Mean: "그녀는 재능 있는 젊은 예술가에요.",
  },
  {
    Word: "Right",
    Word_Meaning: "옳은",
    English_Sentence: "Is this the right way to the museum?",
    English_Sentence_Mean: "이게 박물관으로 가는 올바른 길인가요?",
  },
  {
    Word: "Wrong",
    Word_Meaning: "틀린",
    English_Sentence: "I'm afraid you're wrong about that.",
    English_Sentence_Mean: "그에 대해 당신이 틀렸다고 생각해요.",
  },
  {
    Word: "True",
    Word_Meaning: "진실한",
    English_Sentence: "His words turned out to be true.",
    English_Sentence_Mean: "그의 말은 사실로 드러났어.",
  },
  {
    Word: "False",
    Word_Meaning: "거짓의",
    English_Sentence: "The information provided was false.",
    English_Sentence_Mean: "제공된 정보는 거짓이었어.",
  },
];
