export const Day3Word = [
  {
    Word: "Sad",
    Word_Meaning: "슬픈",
    English_Sentence: "She felt sad after watching the movie.",
    English_Sentence_Mean: "그녀는 그 영화를 보고 슬펐어.",
  },
  {
    Word: "Angry",
    Word_Meaning: "화난",
    English_Sentence: "He gets angry when things go wrong.",
    English_Sentence_Mean: "일이 잘 안 풀릴 때 그는 화를 낸다.",
  },
  {
    Word: "Excited",
    Word_Meaning: "흥분한",
    English_Sentence: "I'm excited about the upcoming trip.",
    English_Sentence_Mean: "다가오는 여행에 나는 흥분해.",
  },
  {
    Word: "Bored",
    Word_Meaning: "심심한",
    English_Sentence: "She felt bored during the long lecture.",
    English_Sentence_Mean: "긴 강의 동안 그녀는 심심함을 느꼈다.",
  },
  {
    Word: "Tired",
    Word_Meaning: "피곤한",
    English_Sentence: "I'm too tired to go out tonight.",
    English_Sentence_Mean: "오늘 밤 나는 너무 피곤해 나가기 싫어.",
  },
  {
    Word: "Energetic",
    Word_Meaning: "활기찬",
    English_Sentence: "After a good night's sleep, I feel energetic.",
    English_Sentence_Mean: "좋은 밤 잠을 자고 나면 나는 활기차게 느껴져.",
  },
  {
    Word: "Quiet",
    Word_Meaning: "조용한",
    English_Sentence: "The library is a quiet place to study.",
    English_Sentence_Mean: "도서관은 공부하기에 조용한 장소다.",
  },
  {
    Word: "Loud",
    Word_Meaning: "시끄러운",
    English_Sentence: "The concert was so loud, but I enjoyed it.",
    English_Sentence_Mean: "콘서트는 너무 시끄러웠지만, 나는 즐겼다.",
  },
  {
    Word: "Soft",
    Word_Meaning: "부드러운",
    English_Sentence: "The baby's skin is soft.",
    English_Sentence_Mean: "아기의 피부는 부드러워.",
  },
  {
    Word: "Hard",
    Word_Meaning: "단단한",
    English_Sentence: "The rock is hard to break.",
    English_Sentence_Mean: "그 바위는 부수기 어려워.",
  },
  {
    Word: "Easy",
    Word_Meaning: "쉬운",
    English_Sentence: "Learning a new language is not always easy.",
    English_Sentence_Mean: "새로운 언어를 배우는 것은 항상 쉬운 일이 아니다.",
  },
  {
    Word: "Difficult",
    Word_Meaning: "어려운",
    English_Sentence: "The math problem was difficult to solve.",
    English_Sentence_Mean: "수학 문제는 해결하기 어려웠다.",
  },
  {
    Word: "Simple",
    Word_Meaning: "간단한",
    English_Sentence: "Cooking this recipe is simple.",
    English_Sentence_Mean: "이 레시피 요리는 간단하다.",
  },
  {
    Word: "Complex",
    Word_Meaning: "복잡한",
    English_Sentence: "The instructions were complex and hard to follow.",
    English_Sentence_Mean: "그 지시사항은 복잡해서 따르기 어려웠다.",
  },
  {
    Word: "Open",
    Word_Meaning: "열린",
    English_Sentence: "Please leave the door open.",
    English_Sentence_Mean: "문을 열어두세요.",
  },
  {
    Word: "Closed",
    Word_Meaning: "닫힌",
    English_Sentence: "The shop is closed on Sundays.",
    English_Sentence_Mean: "가게는 일요일에 문을 닫아요.",
  },
  {
    Word: "Free",
    Word_Meaning: "자유로운",
    English_Sentence: "The birds fly free in the sky.",
    English_Sentence_Mean: "새들은 하늘을 자유롭게 날아다닌다.",
  },
  {
    Word: "Expensive",
    Word_Meaning: "비싼",
    English_Sentence: "Designer clothes are often expensive.",
    English_Sentence_Mean: "디자이너 의류는 종종 비싸다.",
  },
  {
    Word: "Cheap",
    Word_Meaning: "싼",
    English_Sentence: "I found a cheap hotel for our trip.",
    English_Sentence_Mean: "여행을 위해 싼 호텔을 찾았어.",
  },
  {
    Word: "Rich",
    Word_Meaning: "부유한",
    English_Sentence: "He became rich after starting his own business.",
    English_Sentence_Mean: "자기 사업을 시작한 후 그는 부유해졌다.",
  },
  {
    Word: "Poor",
    Word_Meaning: "가난한",
    English_Sentence: "Many people are working hard to help the poor.",
    English_Sentence_Mean:
      "많은 사람들이 가난한 이들을 돕기 위해 열심히 일하고 있다.",
  },
  {
    Word: "Big",
    Word_Meaning: "큰",
    English_Sentence: "The elephant is big and strong.",
    English_Sentence_Mean: "코끼리는 크고 강하다.",
  },
  {
    Word: "Small",
    Word_Meaning: "작은",
    English_Sentence: "I have a small garden in my backyard.",
    English_Sentence_Mean: "나는 뒷마당에 작은 정원이 있다.",
  },
  {
    Word: "Long",
    Word_Meaning: "긴",
    English_Sentence: "The river is long and winding.",
    English_Sentence_Mean: "그 강은 길고 구불구불하다.",
  },
  {
    Word: "Short",
    Word_Meaning: "짧은",
    English_Sentence: "She has short hair now.",
    English_Sentence_Mean: "그녀는 이제 짧은 머리다.",
  },
  {
    Word: "Tall",
    Word_Meaning: "키가 큰",
    English_Sentence: "The basketball player is very tall.",
    English_Sentence_Mean: "농구 선수는 매우 키가 크다.",
  },
  {
    Word: "Short",
    Word_Meaning: "키가 작은",
    English_Sentence: "My sister is short compared to me.",
    English_Sentence_Mean: "나에 비해 내 동생은 키가 작아.",
  },
  {
    Word: "Heavy",
    Word_Meaning: "무거운",
    English_Sentence: "The box is too heavy to lift alone.",
    English_Sentence_Mean: "이 상자는 혼자 들기에 너무 무겁다.",
  },
  {
    Word: "Light",
    Word_Meaning: "가벼운",
    English_Sentence: "The feather is very light.",
    English_Sentence_Mean: "그 깃털은 매우 가볍다.",
  },
  {
    Word: "Deep",
    Word_Meaning: "깊은",
    English_Sentence: "The lake is deep in the middle.",
    English_Sentence_Mean: "그 호수는 가운데가 깊다.",
  },
  {
    Word: "Shallow",
    Word_Meaning: "얕은",
    English_Sentence: "Be careful, the water is shallow here.",
    English_Sentence_Mean: "조심해, 이곳은 물이 얕아.",
  },
  {
    Word: "Wide",
    Word_Meaning: "넓은",
    English_Sentence: "The road is wide enough for two cars.",
    English_Sentence_Mean: "길은 두 대의 차가 지날만큼 넓다.",
  },
  {
    Word: "Narrow",
    Word_Meaning: "좁은",
    English_Sentence: "The alley is narrow and dark.",
    English_Sentence_Mean: "골목은 좁고 어두워.",
  },
  {
    Word: "Far",
    Word_Meaning: "멀리 떨어진",
    English_Sentence: "The mountain is far in the distance.",
    English_Sentence_Mean: "산은 멀리 떨어져 있다.",
  },
  {
    Word: "Near",
    Word_Meaning: "가까운",
    English_Sentence: "The grocery store is near my house.",
    English_Sentence_Mean: "식료품 점은 내 집 근처에 있다.",
  },
  {
    Word: "Day",
    Word_Meaning: "날",
    English_Sentence: "Today is a beautiful day.",
    English_Sentence_Mean: "오늘은 아름다운 날이다.",
  },
  {
    Word: "Night",
    Word_Meaning: "밤",
    English_Sentence: "I love watching the stars at night.",
    English_Sentence_Mean: "나는 밤에 별을 보는 것을 좋아해.",
  },
  {
    Word: "Morning",
    Word_Meaning: "아침",
    English_Sentence: "I like to have coffee in the morning.",
    English_Sentence_Mean: "나는 아침에 커피를 마시는 것을 좋아해.",
  },
  {
    Word: "Afternoon",
    Word_Meaning: "오후",
    English_Sentence: "We'll meet in the afternoon.",
    English_Sentence_Mean: "우리는 오후에 만날 거야.",
  },
  {
    Word: "Evening",
    Word_Meaning: "저녁",
    English_Sentence: "Let's have dinner together this evening.",
    English_Sentence_Mean: "오늘 저녁에 함께 저녁을 먹자.",
  },
  {
    Word: "Today",
    Word_Meaning: "오늘",
    English_Sentence: "What are your plans for today?",
    English_Sentence_Mean: "오늘의 계획은 뭐에요?",
  },
  {
    Word: "Yesterday",
    Word_Meaning: "어제",
    English_Sentence: "I visited the museum yesterday.",
    English_Sentence_Mean: "나는 어제 박물관을 방문했다.",
  },
  {
    Word: "Tomorrow",
    Word_Meaning: "내일",
    English_Sentence: "We have a meeting tomorrow.",
    English_Sentence_Mean: "우리는 내일 회의가 있다.",
  },
  {
    Word: "Week",
    Word_Meaning: "주",
    English_Sentence: "I have a busy week ahead.",
    English_Sentence_Mean: "나는 앞으로 바쁜 주가 있어.",
  },
  {
    Word: "Month",
    Word_Meaning: "달",
    English_Sentence: "My birthday is next month.",
    English_Sentence_Mean: "내 생일은 다음 달이다.",
  },
  {
    Word: "Year",
    Word_Meaning: "년",
    English_Sentence: "We're planning a trip next year.",
    English_Sentence_Mean: "우리는 내년에 여행 계획 중이다.",
  },
  {
    Word: "Minute",
    Word_Meaning: "분",
    English_Sentence: "I'll be back in a minute.",
    English_Sentence_Mean: "나는 곧 돌아올게.",
  },
  {
    Word: "Second",
    Word_Meaning: "초",
    English_Sentence: "The race was won by a split second.",
    English_Sentence_Mean: "그 경주는 스플릿 초 단위로 이겼다.",
  },
  {
    Word: "Hour",
    Word_Meaning: "시간",
    English_Sentence: "The movie is two hours long.",
    English_Sentence_Mean: "그 영화는 두 시간이 걸려.",
  },
];
