export const Day4Word = [
  {
    Word: "Clock",
    Word_Meaning: "시계",
    English_Sentence: "I glanced at the clock and realized I was late.",
    English_Sentence_Mean: "나는 시계를 훑어보고 내가 늦었다는 것을 깨달았다.",
  },
  {
    Word: "Watch",
    Word_Meaning: "손목시계",
    English_Sentence: "She received a beautiful watch as a birthday gift.",
    English_Sentence_Mean: "그녀는 생일 선물로 아름다운 손목시계를 받았다.",
  },
  {
    Word: "Calendar",
    Word_Meaning: "달력",
    English_Sentence: "I marked the date on the calendar for our meeting.",
    English_Sentence_Mean: "나는 우리의 미팅을 위해 달력에 날짜를 표시했다.",
  },
  {
    Word: "Sun",
    Word_Meaning: "태양",
    English_Sentence: "The sun rises in the east and sets in the west.",
    English_Sentence_Mean: "태양은 동쪽에서 떠오르고 서쪽에서 지는데.",
  },
  {
    Word: "Moon",
    Word_Meaning: "달",
    English_Sentence: "The moon was full and bright in the night sky.",
    English_Sentence_Mean: "달은 밤하늘에 가득 차고 밝았다.",
  },
  {
    Word: "Star",
    Word_Meaning: "별",
    English_Sentence: "We gazed at the stars on a clear summer night.",
    English_Sentence_Mean: "우리는 맑은 여름 밤에 별들을 바라보았다.",
  },
  {
    Word: "Sky",
    Word_Meaning: "하늘",
    English_Sentence: "The sky was painted in shades of pink during sunset.",
    English_Sentence_Mean: "저녁 노을 동안 하늘은 핑크빛으로 칠해져 있었다.",
  },
  {
    Word: "Cloud",
    Word_Meaning: "구름",
    English_Sentence: "Dark clouds gathered before the storm.",
    English_Sentence_Mean: "폭풍전에 어두운 구름이 모였다.",
  },
  {
    Word: "Rain",
    Word_Meaning: "비",
    English_Sentence: "We decided to stay indoors due to heavy rain.",
    English_Sentence_Mean: "우리는 he비로 인해 실내에 머물기로 결정했다.",
  },
  {
    Word: "Snow",
    Word_Meaning: "눈",
    English_Sentence: "Children love playing in the snow during winter.",
    English_Sentence_Mean: "겨울에 어린이들은 눈에서 놀기를 좋아한다.",
  },
  {
    Word: "Wind",
    Word_Meaning: "바람",
    English_Sentence: "The wind rustled the leaves on the trees.",
    English_Sentence_Mean: "바람이 나무의 잎을 속삭이듯 흔들었다.",
  },
  {
    Word: "Storm",
    Word_Meaning: "폭풍",
    English_Sentence: "The ship faced a fierce storm on the open sea.",
    English_Sentence_Mean: "그 배는 열린 바다에서 거센 폭풍에 직면했다.",
  },
  {
    Word: "Thunder",
    Word_Meaning: "천둥",
    English_Sentence: "The loud thunder scared the children.",
    English_Sentence_Mean: "크고 시끄러운 천둥 소리가 어린이들을 놀래켰다.",
  },
  {
    Word: "Lightning",
    Word_Meaning: "번개",
    English_Sentence: "We saw a flash of lightning before the rain started.",
    English_Sentence_Mean:
      "우리는 비가 시작되기 전에 번개가 번쩍이는 것을 보았다.",
  },
  {
    Word: "Fire",
    Word_Meaning: "불",
    English_Sentence: "The fire warmed us on a cold winter night.",
    English_Sentence_Mean: "그 불은 추운 겨울 밤에 우리를 따뜻하게 해 주었다.",
  },
  {
    Word: "Water",
    Word_Meaning: "물",
    English_Sentence: "You should drink plenty of water every day.",
    English_Sentence_Mean: "매일 충분한 물을 마셔야 해.",
  },
  {
    Word: "Ice",
    Word_Meaning: "얼음",
    English_Sentence: "I put ice in my drink to make it cold.",
    English_Sentence_Mean: "나는 음료에 얼음을 넣어 차갑게 했다.",
  },
  {
    Word: "Air",
    Word_Meaning: "공기",
    English_Sentence: "Fresh air is good for your health.",
    English_Sentence_Mean: "신선한 공기는 건강에 좋다.",
  },
  {
    Word: "Earth",
    Word_Meaning: "지구",
    English_Sentence: "We must take care of the Earth for future generations.",
    English_Sentence_Mean: "우리는 미래 세대를 위해 지구를 보호해야 한다.",
  },
  {
    Word: "Land",
    Word_Meaning: "땅",
    English_Sentence: "The land was fertile and suitable for farming.",
    English_Sentence_Mean: "그 땅은 비옥하고 농업에 적합했다.",
  },
  {
    Word: "Sea",
    Word_Meaning: "바다",
    English_Sentence: "The sea stretches out as far as the eye can see.",
    English_Sentence_Mean: "눈이 볼 수 있는 한 바다는 멀리 펼쳐져 있다.",
  },
  {
    Word: "Mountain",
    Word_Meaning: "산",
    English_Sentence:
      "They climbed the mountain to enjoy the view from the top.",
    English_Sentence_Mean: "그들은 산을 오르려고 꼭대기에서의 전망을 즐겼다.",
  },
  {
    Word: "Valley",
    Word_Meaning: "계곡",
    English_Sentence: "The valley was surrounded by tall mountains.",
    English_Sentence_Mean: "계곡은 키 큰 산으로 둘러싸여 있었다.",
  },
  {
    Word: "Forest",
    Word_Meaning: "숲",
    English_Sentence: "Many animals live in the dense forest.",
    English_Sentence_Mean: "많은 동물들이 무성한 숲에서 살고 있다.",
  },
  {
    Word: "Desert",
    Word_Meaning: "사막",
    English_Sentence: "Camels are well-adapted to life in the desert.",
    English_Sentence_Mean: "낙타는 사막에서의 삶에 잘 적응되어 있다.",
  },
  {
    Word: "Beach",
    Word_Meaning: "해변",
    English_Sentence: "We spent the day relaxing on the sandy beach.",
    English_Sentence_Mean: "우리는 모래사장에서 편안한 시간을 보냈다.",
  },
  {
    Word: "River",
    Word_Meaning: "강",
    English_Sentence: "The river flowed gently through the meadow.",
    English_Sentence_Mean: "그 강은 목초지를 부드럽게 흐르고 있었다.",
  },
  {
    Word: "Lake",
    Word_Meaning: "호수",
    English_Sentence:
      "The lake reflects the beauty of the surrounding mountains.",
    English_Sentence_Mean: "그 호수는 주변 산의 아름다움을 반영하고 있다.",
  },
  {
    Word: "Pond",
    Word_Meaning: "연못",
    English_Sentence: "The pond is home to various aquatic plants.",
    English_Sentence_Mean: "그 연못은 다양한 수생 식물의 서식지이다.",
  },
  {
    Word: "Ocean",
    Word_Meaning: "대양",
    English_Sentence: "The ocean covers more than 70% of the Earth's surface.",
    English_Sentence_Mean: "대양은 지구 표면의 70% 이상을 차지하고 있다.",
  },
  {
    Word: "Island",
    Word_Meaning: "섬",
    English_Sentence: "They explored the uninhabited island.",
    English_Sentence_Mean: "그들은 무인도를 탐험했다.",
  },
  {
    Word: "Continent",
    Word_Meaning: "대륙",
    English_Sentence: "Africa is the second-largest continent in the world.",
    English_Sentence_Mean: "아프리카는 세계에서 두 번째로 큰 대륙이다.",
  },
  {
    Word: "Country",
    Word_Meaning: "나라",
    English_Sentence: "Each country has its own unique culture.",
    English_Sentence_Mean: "각 나라는 고유한 문화를 가지고 있다.",
  },
  {
    Word: "City",
    Word_Meaning: "도시",
    English_Sentence: "New York is a bustling city that never sleeps.",
    English_Sentence_Mean: "뉴욕은 한 순간도 멈추지 않는 북적거리는 도시이다.",
  },
  {
    Word: "Town",
    Word_Meaning: "마을",
    English_Sentence: "The small town had a charming, quaint atmosphere.",
    English_Sentence_Mean:
      "작은 마을은 매력적이고 고요한 분위기를 가지고 있었다.",
  },
  {
    Word: "Village",
    Word_Meaning: "마을",
    English_Sentence: "The village was surrounded by green fields.",
    English_Sentence_Mean: "그 마을은 초록빛 들판으로 둘러싸여 있었다.",
  },
  {
    Word: "Street",
    Word_Meaning: "거리",
    English_Sentence: "The street was lined with shops and cafes.",
    English_Sentence_Mean: "거리 양쪽에는 상점과 카페가 늘어선 상태였다.",
  },
  {
    Word: "Road",
    Word_Meaning: "도로",
    English_Sentence: "We took a scenic road trip through the mountains.",
    English_Sentence_Mean: "우리는 산을 따라 경치 좋은 도로 여행을 했다.",
  },
  {
    Word: "Highway",
    Word_Meaning: "고속도로",
    English_Sentence: "The highway allows for fast travel between cities.",
    English_Sentence_Mean: "고속도로는 도시 간의 빠른 이동을 가능하게 한다.",
  },
  {
    Word: "Bridge",
    Word_Meaning: "다리",
    English_Sentence: "The bridge spanned across the wide river.",
    English_Sentence_Mean: "그 다리는 큰 강을 가로지르고 있었다.",
  },
  {
    Word: "Tunnel",
    Word_Meaning: "터널",
    English_Sentence: "The train entered a dark tunnel.",
    English_Sentence_Mean: "기차는 어두운 터널에 들어갔다.",
  },
  {
    Word: "Building",
    Word_Meaning: "건물",
    English_Sentence: "The city skyline is filled with tall buildings.",
    English_Sentence_Mean: "도시의 지평선은 키 큰 건물로 가득하다.",
  },
  {
    Word: "House",
    Word_Meaning: "집",
    English_Sentence: "The house has a beautiful garden in the backyard.",
    English_Sentence_Mean: "집 뒷마당에는 아름다운 정원이 있다.",
  },
  {
    Word: "Apartment",
    Word_Meaning: "아파트",
    English_Sentence: "She lives in a cozy apartment in the city center.",
    English_Sentence_Mean: "그녀는 도심의 아늑한 아파트에 살고 있다.",
  },
  {
    Word: "Room",
    Word_Meaning: "방",
    English_Sentence: "The hotel room had a stunning view of the ocean.",
    English_Sentence_Mean: "그 호텔 방은 바다의 멋진 전망을 가지고 있었다.",
  },
  {
    Word: "Kitchen",
    Word_Meaning: "부엌",
    English_Sentence: "She enjoys cooking in her spacious kitchen.",
    English_Sentence_Mean: "그녀는 넓은 부엌에서 요리하는 것을 즐긴다.",
  },
  {
    Word: "Bathroom",
    Word_Meaning: "화장실",
    English_Sentence: "The bathroom was equipped with modern amenities.",
    English_Sentence_Mean: "화장실은 현대적인 시설로 갖춰져 있었다.",
  },
  {
    Word: "Bedroom",
    Word_Meaning: "침실",
    English_Sentence: "The bedroom was decorated in calming colors.",
    English_Sentence_Mean: "침실은 안정적인 색으로 꾸며져 있었다.",
  },
  {
    Word: "Living room",
    Word_Meaning: "거실",
    English_Sentence: "The family gathered in the living room for movie night.",
    English_Sentence_Mean: "가족은 영화 밤을 위해 거실에 모였다.",
  },
];
