export const Day6Word = [
  {
    Word: "Popular",
    Word_Meaning: "인기 있는",
    English_Sentence: "The song became popular worldwide.",
    English_Sentence_Mean: "그 노래는 전 세계에서 인기를 얻었다.",
  },
  {
    Word: "Trending",
    Word_Meaning: "트렌드인",
    English_Sentence: "The hashtag was trending on social media.",
    English_Sentence_Mean: "해시태그가 소셜 미디어에서 트렌드로 올라갔다.",
  },
  {
    Word: "News",
    Word_Meaning: "뉴스",
    English_Sentence: "I always start my day by reading the news.",
    English_Sentence_Mean: "나는 항상 뉴스를 읽으며 하루를 시작한다.",
  },
  {
    Word: "Headline",
    Word_Meaning: "헤드라인",
    English_Sentence: "The headline of the article caught my attention.",
    English_Sentence_Mean: "기사의 헤드라인이 내 주의를 끌었다.",
  },
  {
    Word: "Article",
    Word_Meaning: "기사",
    English_Sentence: "She wrote an insightful article on climate change.",
    English_Sentence_Mean: "그녀는 기후 변화에 관한 통찰력 있는 기사를 썼다.",
  },
  {
    Word: "Report",
    Word_Meaning: "보도",
    English_Sentence: "The report provides detailed information on the issue.",
    English_Sentence_Mean: "그 보도는 해당 문제에 대한 자세한 정보를 제공한다.",
  },
  {
    Word: "Journalist",
    Word_Meaning: "기자",
    English_Sentence: "The journalist interviewed the famous actor.",
    English_Sentence_Mean: "그 기자는 유명한 배우에게 인터뷰했다.",
  },
  {
    Word: "Interview",
    Word_Meaning: "인터뷰",
    English_Sentence: "I have an interview for a job tomorrow.",
    English_Sentence_Mean: "내일 나는 직장 면접이 있다.",
  },
  {
    Word: "Question",
    Word_Meaning: "질문",
    English_Sentence: "She asked a thought-provoking question.",
    English_Sentence_Mean: "그녀는 생각을 일으키는 질문을 했다.",
  },
  {
    Word: "Answer",
    Word_Meaning: "답변",
    English_Sentence: "I couldn't find the right answer to the puzzle.",
    English_Sentence_Mean: "나는 그 퍼즐에 대한 올바른 답을 찾지 못했다.",
  },
  {
    Word: "Fact",
    Word_Meaning: "사실",
    English_Sentence: "It's essential to distinguish fact from opinion.",
    English_Sentence_Mean: "사실과 의견을 구별하는 것이 중요하다.",
  },
  {
    Word: "Opinion",
    Word_Meaning: "의견",
    English_Sentence: "Everyone is entitled to their own opinion.",
    English_Sentence_Mean: "모든 사람은 자신만의 의견을 가지고 있다.",
  },
  {
    Word: "View",
    Word_Meaning: "견해",
    English_Sentence: "His view on the matter is quite different.",
    English_Sentence_Mean: "그의 그 문제에 대한 견해는 매우 다르다.",
  },
  {
    Word: "Perspective",
    Word_Meaning: "관점",
    English_Sentence: "Each person has a unique perspective on life.",
    English_Sentence_Mean: "각 개인은 삶에 대한 독특한 관점을 가지고 있다.",
  },
  {
    Word: "Idea",
    Word_Meaning: "아이디어",
    English_Sentence: "He shared his idea for a new project.",
    English_Sentence_Mean: "그는 새로운 프로젝트에 대한 아이디어를 공유했다.",
  },
  {
    Word: "Thought",
    Word_Meaning: "생각",
    English_Sentence: "Deep thoughts often come during quiet moments.",
    English_Sentence_Mean: "깊은 생각은 종종 조용한 순간에 찾아온다.",
  },
  {
    Word: "Mind",
    Word_Meaning: "마음",
    English_Sentence: "Clear your mind for better concentration.",
    English_Sentence_Mean: "집중력을 높이려면 마음을 비워라.",
  },
  {
    Word: "Brain",
    Word_Meaning: "뇌",
    English_Sentence:
      "The brain is a complex organ that controls many functions.",
    English_Sentence_Mean: "뇌는 많은 기능을 조절하는 복잡한 기관이다.",
  },
  {
    Word: "Intelligence",
    Word_Meaning: "지능",
    English_Sentence: "Intelligence involves problem-solving and learning.",
    English_Sentence_Mean: "지능은 문제 해결과 학습을 포함한다.",
  },
  {
    Word: "Knowledge",
    Word_Meaning: "지식",
    English_Sentence: "Continuous learning expands your knowledge.",
    English_Sentence_Mean: "지속적인 학습은 지식을 확장시킨다.",
  },
  {
    Word: "Wisdom",
    Word_Meaning: "지혜",
    English_Sentence: "Wisdom comes from experience and reflection.",
    English_Sentence_Mean: "지혜는 경험과 깊은 생각에서 나온다.",
  },
  {
    Word: "Experience",
    Word_Meaning: "경험",
    English_Sentence: "Traveling is a valuable experience.",
    English_Sentence_Mean: "여행은 값진 경험이다.",
  },
  {
    Word: "Skill",
    Word_Meaning: "기술",
    English_Sentence: "Developing a new skill takes time and practice.",
    English_Sentence_Mean:
      "새로운 기술을 개발하는 데는 시간과 연습이 필요하다.",
  },
  {
    Word: "Talent",
    Word_Meaning: "재능",
    English_Sentence: "She has a natural talent for playing the piano.",
    English_Sentence_Mean:
      "그녀는 피아노 연주에 대한 자연스러운 재능을 가지고 있다.",
  },
  {
    Word: "Ability",
    Word_Meaning: "능력",
    English_Sentence: "Improving your ability requires consistent effort.",
    English_Sentence_Mean: "능력을 향상시키려면 일관된 노력이 필요하다.",
  },
  {
    Word: "Strength",
    Word_Meaning: "힘",
    English_Sentence: "Physical and mental strength go hand in hand.",
    English_Sentence_Mean: "신체적인 힘과 정신적인 힘은 서로 연결돼 있다.",
  },
  {
    Word: "Weakness",
    Word_Meaning: "약점",
    English_Sentence:
      "Recognizing your weakness is the first step to improvement.",
    English_Sentence_Mean: "자신의 약점을 인지하는 것은 개선의 첫걸음이다.",
  },
  {
    Word: "Courage",
    Word_Meaning: "용기",
    English_Sentence: "Facing challenges requires courage.",
    English_Sentence_Mean: "도전에 맞서기 위해서는 용기가 필요하다.",
  },
  {
    Word: "Fear",
    Word_Meaning: "두려움",
    English_Sentence: "Overcoming fear is a personal triumph.",
    English_Sentence_Mean: "두려움을 극복하는 것은 개인적인 승리이다.",
  },
  {
    Word: "Confidence",
    Word_Meaning: "자신감",
    English_Sentence: "Confidence is key to success.",
    English_Sentence_Mean: "자신감은 성공의 열쇠이다.",
  },
  {
    Word: "Doubt",
    Word_Meaning: "의심",
    English_Sentence: "She had a moment of doubt before making the decision.",
    English_Sentence_Mean: "그녀는 결정을 내리기 전에 의심의 순간을 가졌다.",
  },
  {
    Word: "Hope",
    Word_Meaning: "희망",
    English_Sentence: "Hope keeps us motivated for a better future.",
    English_Sentence_Mean: "희망은 우리를 더 나은 미래로 동기부여한다.",
  },
  {
    Word: "Dream",
    Word_Meaning: "꿈",
    English_Sentence: "Chasing your dreams requires dedication.",
    English_Sentence_Mean: "자신의 꿈을 추구하려면 헌신이 필요하다.",
  },
  {
    Word: "Goal",
    Word_Meaning: "목표",
    English_Sentence: "Setting clear goals helps in achieving success.",
    English_Sentence_Mean:
      "명확한 목표를 세우는 것은 성공을 달성하는 데 도움이 된다.",
  },
  {
    Word: "Plan",
    Word_Meaning: "계획",
    English_Sentence: "A well-thought-out plan leads to effective outcomes.",
    English_Sentence_Mean: "심사숙고한 계획은 효과적인 결과로 이끈다.",
  },
  {
    Word: "Strategy",
    Word_Meaning: "전략",
    English_Sentence: "Business success often involves a good strategy.",
    English_Sentence_Mean: "사업 성공은 종종 좋은 전략이 필요하다.",
  },
  {
    Word: "Tactic",
    Word_Meaning: "전술",
    English_Sentence: "Choosing the right tactic is crucial in a game.",
    English_Sentence_Mean: "올바른 전술을 선택하는 것은 게임에서 중요하다.",
  },
  {
    Word: "Action",
    Word_Meaning: "행동",
    English_Sentence: "Taking action is the first step towards change.",
    English_Sentence_Mean: "행동을 취하는 것은 변화로 향하는 첫걸음이다.",
  },
  {
    Word: "Reaction",
    Word_Meaning: "반응",
    English_Sentence: "Her reaction to the surprise was priceless.",
    English_Sentence_Mean: "놀라움에 대한 그녀의 반응은 값진 것이었다.",
  },
  {
    Word: "Decision",
    Word_Meaning: "결정",
    English_Sentence: "Making a decision requires careful consideration.",
    English_Sentence_Mean: "결정을 내리려면 신중한 고려가 필요하다.",
  },
  {
    Word: "Choice",
    Word_Meaning: "선택",
    English_Sentence: "Having the freedom to make choices is empowering.",
    English_Sentence_Mean:
      "선택을 할 자유가 있다는 것은 자기 결정력을 키우는 것이다.",
  },
  {
    Word: "Option",
    Word_Meaning: "옵션",
    English_Sentence: "Consider all available options before deciding.",
    English_Sentence_Mean: "결정하기 전에 모든 가능한 옵션을 고려하라.",
  },
  {
    Word: "Solution",
    Word_Meaning: "해결책",
    English_Sentence: "Finding a solution requires creative thinking.",
    English_Sentence_Mean: "해결책을 찾으려면 창의적 사고가 필요하다.",
  },
  {
    Word: "Problem",
    Word_Meaning: "문제",
    English_Sentence: "Addressing the problem is the first step to a solution.",
    English_Sentence_Mean: "문제에 대처하는 것은 해결책으로 가는 첫걸음이다.",
  },
  {
    Word: "Challenge",
    Word_Meaning: "도전",
    English_Sentence: "Embracing challenges leads to personal growth.",
    English_Sentence_Mean: "도전을 수용하는 것은 개인적인 성장으로 이어진다.",
  },
  {
    Word: "Difficulty",
    Word_Meaning: "어려움",
    English_Sentence: "Overcoming difficulties builds resilience.",
    English_Sentence_Mean: "어려움을 극복하는 것은 회복력을 쌓는다.",
  },
  {
    Word: "Obstacle",
    Word_Meaning: "장애물",
    English_Sentence: "Every obstacle can be turned into an opportunity.",
    English_Sentence_Mean: "모든 장애물은 기회로 변할 수 있다.",
  },
  {
    Word: "Opportunity",
    Word_Meaning: "기회",
    English_Sentence: "Seize the opportunity when it comes your way.",
    English_Sentence_Mean: "기회가 찾아올 때 그것을 잡아라.",
  },
  {
    Word: "Risk",
    Word_Meaning: "위험",
    English_Sentence: "Taking calculated risks can lead to success.",
    English_Sentence_Mean: "계획적인 위험을 감수하면 성공으로 이끌 수 있다.",
  },
];
