export const oxDay10 = [
  {
    English_Word: "Feeling",
    Korean_Mean: "감정",
    Options: ["Emotion", "Feeling", "Sensation", "Sentiment"],
    Options_Korean_Mean: ["검은", "감정", "감각", "사진"],
    Correct_Answer: "Feeling",
    Correct_Answer_Korean_Mean: "감정",
  },
  {
    English_Word: "Sentiment",
    Korean_Mean: "감성",
    Options: ["Emotion", "Sentiment", "Feeling", "Mood"],
    Options_Korean_Mean: ["감정", "감성", "색깔", "기분"],
    Correct_Answer: "Sentiment",
    Correct_Answer_Korean_Mean: "감성",
  },
  {
    English_Word: "Mood",
    Korean_Mean: "기분",
    Options: ["Temperament", "Mood", "Disposition", "Feeling"],
    Options_Korean_Mean: ["성격", "기분", "기질", "감정"],
    Correct_Answer: "Mood",
    Correct_Answer_Korean_Mean: "기분",
  },
  {
    English_Word: "Temperament",
    Korean_Mean: "기질",
    Options: ["Disposition", "Temperament", "Mood", "Character"],
    Options_Korean_Mean: ["성향", "기질", "기분", "성격"],
    Correct_Answer: "Temperament",
    Correct_Answer_Korean_Mean: "기질",
  },
  {
    English_Word: "Personality",
    Korean_Mean: "성격",
    Options: ["Character", "Personality", "Temperament", "Nature"],
    Options_Korean_Mean: ["성격", "대비", "기질", "성질"],
    Correct_Answer: "Personality",
    Correct_Answer_Korean_Mean: "성격",
  },
  {
    English_Word: "Character",
    Korean_Mean: "케릭터",
    Options: ["Nature", "Character", "Personality", "Individuality"],
    Options_Korean_Mean: ["본성", "케릭터", "비밀", "개성"],
    Correct_Answer: "Character",
    Correct_Answer_Korean_Mean: "케릭터",
  },
  {
    English_Word: "Behavior",
    Korean_Mean: "행동",
    Options: ["Action", "Boy", "Conduct", "Behavior"],
    Options_Korean_Mean: ["행운", "항의", "마수", "행동"],
    Correct_Answer: "Behavior",
    Correct_Answer_Korean_Mean: "행동",
  },
  {
    English_Word: "Habit",
    Korean_Mean: "습관",
    Options: ["Practice", "Happy", "Routine", "Habit"],
    Options_Korean_Mean: ["연습", "종일", "루틴", "습관"],
    Correct_Answer: "Habit",
    Correct_Answer_Korean_Mean: "습관",
  },
  {
    English_Word: "Routine",
    Korean_Mean: "루틴",
    Options: ["Tradition", "Culture", "Society", "Routine"],
    Options_Korean_Mean: ["전통", "문화", "사회", "루틴"],
    Correct_Answer: "Routine",
    Correct_Answer_Korean_Mean: "루틴",
  },
  {
    English_Word: "Tradition",
    Korean_Mean: "전통",
    Options: ["Culture", "Tradition", "Heritage", "Legacy"],
    Options_Korean_Mean: ["문화", "전통", "유산", "우유"],
    Correct_Answer: "Tradition",
    Correct_Answer_Korean_Mean: "전통",
  },
  {
    English_Word: "Culture",
    Korean_Mean: "문화",
    Options: ["Society", "Community", "Culture", "Civilization"],
    Options_Korean_Mean: ["사회", "공동체", "문화", "문명"],
    Correct_Answer: "Culture",
    Correct_Answer_Korean_Mean: "문화",
  },
  {
    English_Word: "Society",
    Korean_Mean: "사회",
    Options: ["Community", "Group", "Team", "Society"],
    Options_Korean_Mean: ["공동체", "그룹", "팀", "사회"],
    Correct_Answer: "Society",
    Correct_Answer_Korean_Mean: "사회",
  },
  {
    English_Word: "Community",
    Korean_Mean: "공동체",
    Options: ["Association", "Community", "Fellowship", "Union"],
    Options_Korean_Mean: ["협회", "공동체", "연고", "연합"],
    Correct_Answer: "Community",
    Correct_Answer_Korean_Mean: "공동체",
  },
  {
    English_Word: "Group",
    Korean_Mean: "그룹",
    Options: ["Team", "Organization", "Company", "Group"],
    Options_Korean_Mean: ["팀", "조직", "회사", "그룹"],
    Correct_Answer: "Group",
    Correct_Answer_Korean_Mean: "그룹",
  },
  {
    English_Word: "Team",
    Korean_Mean: "팀",
    Options: ["Team", "Company", "Business", "God"],
    Options_Korean_Mean: ["팀", "회사", "비즈니스", "하늘"],
    Correct_Answer: "Team",
    Correct_Answer_Korean_Mean: "팀",
  },
  {
    English_Word: "Organization",
    Korean_Mean: "조직",
    Options: ["Company", "Organization", "Market", "Orange"],
    Options_Korean_Mean: ["회사", "조직", "시장", "기억"],
    Correct_Answer: "Organization",
    Correct_Answer_Korean_Mean: "조직",
  },
  {
    English_Word: "Company",
    Korean_Mean: "회사",
    Options: ["Company", "Market", "Customer", "Dream"],
    Options_Korean_Mean: ["비즈니스", "회사", "고객", "활약"],
    Correct_Answer: "Company",
    Correct_Answer_Korean_Mean: "회사",
  },
  {
    English_Word: "Business",
    Korean_Mean: "비즈니스",
    Options: ["Market", "Customer", "Client", "Business"],
    Options_Korean_Mean: ["시장", "고객", "클라이언트", "비즈니스"],
    Correct_Answer: "Business",
    Correct_Answer_Korean_Mean: "비즈니스",
  },
  {
    English_Word: "Market",
    Korean_Mean: "시장",
    Options: ["Customer", "Client", "Consumer", "Market"],
    Options_Korean_Mean: ["고객", "클라이언트", "소비자", "시장"],
    Correct_Answer: "Market",
    Correct_Answer_Korean_Mean: "시장",
  },
  {
    English_Word: "Customer",
    Korean_Mean: "고객",
    Options: ["Customer", "Consumer", "Product", "Paper"],
    Options_Korean_Mean: ["클라이언트", "고객", "제품", "고릴라"],
    Correct_Answer: "Customer",
    Correct_Answer_Korean_Mean: "고객",
  },
  {
    English_Word: "Client",
    Korean_Mean: "클라이언트",
    Options: ["Consumer", "Product", "Client", "Gold"],
    Options_Korean_Mean: ["소비자", "클라이언트", "서비스", "퀴즈"],
    Correct_Answer: "Client",
    Correct_Answer_Korean_Mean: "클라이언트",
  },
  {
    English_Word: "Consumer",
    Korean_Mean: "소비자",
    Options: ["Product", "Service", "Quality", "Consumer"],
    Options_Korean_Mean: ["제품", "서비스", "품질", "소비자"],
    Correct_Answer: "Consumer",
    Correct_Answer_Korean_Mean: "소비자",
  },
  {
    English_Word: "Product",
    Korean_Mean: "제품",
    Options: ["Product", "Quality", "Quantity", "Green"],
    Options_Korean_Mean: ["제품", "품질", "수량", "컴퓨터"],
    Correct_Answer: "Product",
    Correct_Answer_Korean_Mean: "제품",
  },
  {
    English_Word: "Service",
    Korean_Mean: "서비스",
    Options: ["Quality", "Quantity", "Price", "Service"],
    Options_Korean_Mean: ["품질", "수량", "가격", "서비스"],
    Correct_Answer: "Service",
    Correct_Answer_Korean_Mean: "서비스",
  },
  {
    English_Word: "Quality",
    Korean_Mean: "품질",
    Options: ["Quantity", "Price", "Quality", "Mouse"],
    Options_Korean_Mean: ["수량", "가격", "품질", "노트"],
    Correct_Answer: "Quality",
    Correct_Answer_Korean_Mean: "품질",
  },
  {
    English_Word: "Quantity",
    Korean_Mean: "수량",
    Options: ["Price", "Cost", "Budget", "Quantity"],
    Options_Korean_Mean: ["가격", "비용", "예산", "수량"],
    Correct_Answer: "Quantity",
    Correct_Answer_Korean_Mean: "수량",
  },
  {
    English_Word: "Price",
    Korean_Mean: "가격",
    Options: ["Cost", "Price", "Expense", "Sky"],
    Options_Korean_Mean: ["비용", "가격", "경비", "음식"],
    Correct_Answer: "Price",
    Correct_Answer_Korean_Mean: "가격",
  },
  {
    English_Word: "Cost",
    Korean_Mean: "비용",
    Options: ["Cost", "Expense", "Profit", "Code"],
    Options_Korean_Mean: ["비용", "경비", "이익", "코딩"],
    Correct_Answer: "Cost",
    Correct_Answer_Korean_Mean: "비용",
  },
  {
    English_Word: "Budget",
    Korean_Mean: "예산",
    Options: ["Expense", "Profit", "Budget", "Education"],
    Options_Korean_Mean: ["경비", "예산", "손실", "마약"],
    Correct_Answer: "Budget",
    Correct_Answer_Korean_Mean: "예산",
  },
  {
    English_Word: "Expense",
    Korean_Mean: "경비",
    Options: ["Profit", "Loss", "Investment", "Expense"],
    Options_Korean_Mean: ["이익", "손실", "투자", "경비"],
    Correct_Answer: "Expense",
    Correct_Answer_Korean_Mean: "경비",
  },
  {
    English_Word: "Profit",
    Korean_Mean: "이익",
    Options: ["Profit", "Investment", "Return", "Rose"],
    Options_Korean_Mean: ["이익", "투자", "수익", "하늘"],
    Correct_Answer: "Profit",
    Correct_Answer_Korean_Mean: "이익",
  },
  {
    English_Word: "Loss",
    Korean_Mean: "손실",
    Options: ["Loss", "Return", "Growth", "Air"],
    Options_Korean_Mean: ["손실", "수익", "성장", "발전"],
    Correct_Answer: "Loss",
    Correct_Answer_Korean_Mean: "손실",
  },
  {
    English_Word: "Investment",
    Korean_Mean: "투자",
    Options: ["Return", "Growth", "Development", "Investment"],
    Options_Korean_Mean: ["수익", "성장", "개발", "투자"],
    Correct_Answer: "Investment",
    Correct_Answer_Korean_Mean: "투자",
  },
  {
    English_Word: "Return",
    Korean_Mean: "수익",
    Options: ["Growth", "Development", "Return", "TV"],
    Options_Korean_Mean: ["성장", "개발", "수익", "육체"],
    Correct_Answer: "Return",
    Correct_Answer_Korean_Mean: "수익",
  },
  {
    English_Word: "Growth",
    Korean_Mean: "성장",
    Options: ["Development", "Progress", "Improvement", "Growth"],
    Options_Korean_Mean: ["개발", "진전", "개선", "성장"],
    Correct_Answer: "Growth",
    Correct_Answer_Korean_Mean: "성장",
  },
  {
    English_Word: "Development",
    Korean_Mean: "개발",
    Options: ["Progress", "Development", "Change", "Red"],
    Options_Korean_Mean: ["진전", "개발", "변화", "신비"],
    Correct_Answer: "Development",
    Correct_Answer_Korean_Mean: "개발",
  },
  {
    English_Word: "Progress",
    Korean_Mean: "진전",
    Options: ["Improvement", "Change", "Progress", "Micro"],
    Options_Korean_Mean: ["개선", "진전", "안정", "강아지"],
    Correct_Answer: "Progress",
    Correct_Answer_Korean_Mean: "진전",
  },
  {
    English_Word: "Improvement",
    Korean_Mean: "개선",
    Options: ["Improvement", "Stability", "Balance", "Cat"],
    Options_Korean_Mean: ["개선", "안정", "균형", "도구"],
    Correct_Answer: "Improvement",
    Correct_Answer_Korean_Mean: "개선",
  },
  {
    English_Word: "Change",
    Korean_Mean: "변화",
    Options: ["Stability", "Balance", "Harmony", "Change"],
    Options_Korean_Mean: ["안정", "균형", "조화", "변화"],
    Correct_Answer: "Change",
    Correct_Answer_Korean_Mean: "변화",
  },
  {
    English_Word: "Stability",
    Korean_Mean: "안정",
    Options: ["Balance", "Stability", "Conflict", "Cat"],
    Options_Korean_Mean: ["안정", "조화", "갈등", "집"],
    Correct_Answer: "Stability",
    Correct_Answer_Korean_Mean: "안정",
  },
  {
    English_Word: "Balance",
    Korean_Mean: "균형",
    Options: ["Balance", "Conflict", "Resolution", "Take"],
    Options_Korean_Mean: ["균형", "갈등", "해결", "저항"],
    Correct_Answer: "Balance",
    Correct_Answer_Korean_Mean: "균형",
  },
  {
    English_Word: "Harmony",
    Korean_Mean: "조화",
    Options: ["Conflict", "Harmony", "Agreement", "Hell"],
    Options_Korean_Mean: ["갈등", "조화", "합의", "지옥"],
    Correct_Answer: "Harmony",
    Correct_Answer_Korean_Mean: "조화",
  },
  {
    English_Word: "Conflict",
    Korean_Mean: "갈등",
    Options: ["Conflict", "Agreement", "Disagreement", "Hevean"],
    Options_Korean_Mean: ["갈등", "합의", "불일치", "천국"],
    Correct_Answer: "Conflict",
    Correct_Answer_Korean_Mean: "갈등",
  },
  {
    English_Word: "Resolution",
    Korean_Mean: "해결",
    Options: ["Agreement", "Disagreement", "Argument", "Resolution"],
    Options_Korean_Mean: ["합의", "불일치", "논쟁", "해결"],
    Correct_Answer: "Resolution",
    Correct_Answer_Korean_Mean: "해결",
  },
  {
    English_Word: "Agreement",
    Korean_Mean: "합의",
    Options: ["Agreement", "Argument", "Debate", "Developer"],
    Options_Korean_Mean: ["불일치", "논쟁", "합의", "반대"],
    Correct_Answer: "Agreement",
    Correct_Answer_Korean_Mean: "합의",
  },
  {
    English_Word: "Disagreement",
    Korean_Mean: "불일치",
    Options: ["Argument", "Debate", "Negotiation", "Disagreement"],
    Options_Korean_Mean: ["논쟁", "토론", "협상", "불일치"],
    Correct_Answer: "Disagreement",
    Correct_Answer_Korean_Mean: "불일치",
  },
  {
    English_Word: "Argument",
    Korean_Mean: "논쟁",
    Options: ["Debate", "Argument", "Compromise", "Ruin"],
    Options_Korean_Mean: ["논쟁", "협상", "타협", "검사"],
    Correct_Answer: "Argument",
    Correct_Answer_Korean_Mean: "논쟁",
  },
  {
    English_Word: "Debate",
    Korean_Mean: "토론",
    Options: ["Negotiation", "Compromise", "Collaboration", "Debate"],
    Options_Korean_Mean: ["협상", "타협", "공동 작업", "토론"],
    Correct_Answer: "Debate",
    Correct_Answer_Korean_Mean: "토론",
  },
  {
    English_Word: "Negotiation",
    Korean_Mean: "협상",
    Options: ["Compromise", "Negotiation", "Cooperation", "Noon"],
    Options_Korean_Mean: ["협상", "공동 작업", "협력", "상인"],
    Correct_Answer: "Negotiation",
    Correct_Answer_Korean_Mean: "협상",
  },
];
