export const oxDay2 = [
  {
    English_Word: "Husband",
    Korean_Mean: "남편",
    Options: ["Husband", "Wife", "Boyfriend", "Girlfriend"],
    Options_Korean_Mean: ["남편", "아내", "남자친구", "여자친구"],
    Correct_Answer: "Husband",
    Correct_Answer_Korean_Mean: "남편",
  },
  {
    English_Word: "Wife",
    Korean_Mean: "아내",
    Options: ["Husband", "Wife", "Boyfriend", "Girlfriend"],
    Options_Korean_Mean: ["남편", "아내", "남자친구", "여자친구"],
    Correct_Answer: "Wife",
    Correct_Answer_Korean_Mean: "아내",
  },
  {
    English_Word: "Boyfriend",
    Korean_Mean: "남자친구",
    Options: ["Husband", "Wife", "Boyfriend", "Girlfriend"],
    Options_Korean_Mean: ["남편", "아내", "남자친구", "여자친구"],
    Correct_Answer: "Boyfriend",
    Correct_Answer_Korean_Mean: "남자친구",
  },
  {
    English_Word: "Girlfriend",
    Korean_Mean: "여자친구",
    Options: ["Husband", "Wife", "Boyfriend", "Girlfriend"],
    Options_Korean_Mean: ["남편", "아내", "남자친구", "여자친구"],
    Correct_Answer: "Girlfriend",
    Correct_Answer_Korean_Mean: "여자친구",
  },
  {
    English_Word: "Friend",
    Korean_Mean: "친구",
    Options: ["Friend", "Foe", "Eat", "Drink"],
    Options_Korean_Mean: ["친구", "원수", "먹다", "마시다"],
    Correct_Answer: "Friend",
    Correct_Answer_Korean_Mean: "친구",
  },
  {
    English_Word: "Foe",
    Korean_Mean: "원수",
    Options: ["Friend", "Foe", "Eat", "Drink"],
    Options_Korean_Mean: ["친구", "원수", "먹다", "마시다"],
    Correct_Answer: "Foe",
    Correct_Answer_Korean_Mean: "원수",
  },
  {
    English_Word: "Eat",
    Korean_Mean: "먹다",
    Options: ["Friend", "Foe", "Eat", "Drink"],
    Options_Korean_Mean: ["친구", "원수", "먹다", "마시다"],
    Correct_Answer: "Eat",
    Correct_Answer_Korean_Mean: "먹다",
  },
  {
    English_Word: "Drink",
    Korean_Mean: "마시다",
    Options: ["Friend", "Foe", "Eat", "Drink"],
    Options_Korean_Mean: ["친구", "원수", "먹다", "마시다"],
    Correct_Answer: "Drink",
    Correct_Answer_Korean_Mean: "마시다",
  },
  {
    English_Word: "Sleep",
    Korean_Mean: "자다",
    Options: ["Sleep", "Wake", "Go", "Come"],
    Options_Korean_Mean: ["자다", "깨다", "가다", "오다"],
    Correct_Answer: "Sleep",
    Correct_Answer_Korean_Mean: "자다",
  },
  {
    English_Word: "Wake",
    Korean_Mean: "깨다",
    Options: ["Sleep", "Wake", "Go", "Come"],
    Options_Korean_Mean: ["자다", "깨다", "가다", "오다"],
    Correct_Answer: "Wake",
    Correct_Answer_Korean_Mean: "깨다",
  },
  {
    English_Word: "Go",
    Korean_Mean: "가다",
    Options: ["Go", "Come", "Stop", "Start"],
    Options_Korean_Mean: ["가다", "오다", "멈추다", "시작하다"],
    Correct_Answer: "Go",
    Correct_Answer_Korean_Mean: "가다",
  },
  {
    English_Word: "Come",
    Korean_Mean: "오다",
    Options: ["Go", "Come", "Stop", "Start"],
    Options_Korean_Mean: ["가다", "오다", "멈추다", "시작하다"],
    Correct_Answer: "Come",
    Correct_Answer_Korean_Mean: "오다",
  },
  {
    English_Word: "Stop",
    Korean_Mean: "멈추다",
    Options: ["Go", "Come", "Stop", "Start"],
    Options_Korean_Mean: ["가다", "오다", "멈추다", "시작하다"],
    Correct_Answer: "Stop",
    Correct_Answer_Korean_Mean: "멈추다",
  },
  {
    English_Word: "Start",
    Korean_Mean: "시작하다",
    Options: ["Go", "Come", "Stop", "Start"],
    Options_Korean_Mean: ["가다", "오다", "멈추다", "시작하다"],
    Correct_Answer: "Start",
    Correct_Answer_Korean_Mean: "시작하다",
  },
  {
    English_Word: "Finish",
    Korean_Mean: "끝내다",
    Options: ["Finish", "Work", "Play", "Study"],
    Options_Korean_Mean: ["끝내다", "일하다", "놀다", "공부하다"],
    Correct_Answer: "Finish",
    Correct_Answer_Korean_Mean: "끝내다",
  },
  {
    English_Word: "Work",
    Korean_Mean: "일하다",
    Options: ["Finish", "Work", "Play", "Study"],
    Options_Korean_Mean: ["끝내다", "일하다", "놀다", "공부하다"],
    Correct_Answer: "Work",
    Correct_Answer_Korean_Mean: "일하다",
  },
  {
    English_Word: "Play",
    Korean_Mean: "놀다",
    Options: ["Finish", "Work", "Play", "Study"],
    Options_Korean_Mean: ["끝내다", "일하다", "놀다", "공부하다"],
    Correct_Answer: "Play",
    Correct_Answer_Korean_Mean: "놀다",
  },
  {
    English_Word: "Study",
    Korean_Mean: "공부하다",
    Options: ["Finish", "Work", "Play", "Study"],
    Options_Korean_Mean: ["끝내다", "일하다", "놀다", "공부하다"],
    Correct_Answer: "Study",
    Correct_Answer_Korean_Mean: "공부하다",
  },
  {
    English_Word: "Learn",
    Korean_Mean: "배우다",
    Options: ["Learn", "Teach", "Read", "Write"],
    Options_Korean_Mean: ["배우다", "가르치다", "읽다", "쓰다"],
    Correct_Answer: "Learn",
    Correct_Answer_Korean_Mean: "배우다",
  },
  {
    English_Word: "Teach",
    Korean_Mean: "가르치다",
    Options: ["Learn", "Teach", "Read", "Write"],
    Options_Korean_Mean: ["배우다", "가르치다", "읽다", "쓰다"],
    Correct_Answer: "Teach",
    Correct_Answer_Korean_Mean: "가르치다",
  },
  {
    English_Word: "Read",
    Korean_Mean: "읽다",
    Options: ["Learn", "Teach", "Read", "Write"],
    Options_Korean_Mean: ["배우다", "가르치다", "읽다", "쓰다"],
    Correct_Answer: "Read",
    Correct_Answer_Korean_Mean: "읽다",
  },
  {
    English_Word: "Write",
    Korean_Mean: "쓰다",
    Options: ["Learn", "Teach", "Read", "Write"],
    Options_Korean_Mean: ["배우다", "가르치다", "읽다", "쓰다"],
    Correct_Answer: "Write",
    Correct_Answer_Korean_Mean: "쓰다",
  },
  {
    English_Word: "Speak",
    Korean_Mean: "말하다",
    Options: ["Speak", "Listen", "Watch", "See"],
    Options_Korean_Mean: ["말하다", "듣다", "보다", "전설"],
    Correct_Answer: "Speak",
    Correct_Answer_Korean_Mean: "말하다",
  },
  {
    English_Word: "Listen",
    Korean_Mean: "듣다",
    Options: ["Speak", "Listen", "Watch", "See"],
    Options_Korean_Mean: ["말하다", "듣다", "보다", "하수"],
    Correct_Answer: "Listen",
    Correct_Answer_Korean_Mean: "듣다",
  },
  {
    English_Word: "Watch",
    Korean_Mean: "보다",
    Options: ["Speak", "Listen", "Watch", "See"],
    Options_Korean_Mean: ["말하다", "듣다", "보다", "말"],
    Correct_Answer: "Watch",
    Correct_Answer_Korean_Mean: "보다",
  },
  {
    English_Word: "See",
    Korean_Mean: "보다",
    Options: ["Speak", "Listen", "Watch", "See"],
    Options_Korean_Mean: ["말하다", "듣다", "보다", "수비"],
    Correct_Answer: "See",
    Correct_Answer_Korean_Mean: "보다",
  },
  {
    English_Word: "Hear",
    Korean_Mean: "듣다",
    Options: ["See", "Hear", "Touch", "Smell"],
    Options_Korean_Mean: ["보다", "듣다", "만지다", "냄새 맡다"],
    Correct_Answer: "Hear",
    Correct_Answer_Korean_Mean: "듣다",
  },
  {
    English_Word: "Touch",
    Korean_Mean: "만지다",
    Options: ["See", "Hear", "Touch", "Smell"],
    Options_Korean_Mean: ["보다", "듣다", "만지다", "냄새 맡다"],
    Correct_Answer: "Touch",
    Correct_Answer_Korean_Mean: "만지다",
  },
  {
    English_Word: "Smell",
    Korean_Mean: "냄새 맡다",
    Options: ["See", "Hear", "Touch", "Smell"],
    Options_Korean_Mean: ["보다", "듣다", "만지다", "냄새 맡다"],
    Correct_Answer: "Smell",
    Correct_Answer_Korean_Mean: "냄새 맡다",
  },
  {
    English_Word: "Taste",
    Korean_Mean: "맛을 보다",
    Options: ["Taste", "Feel", "Hot", "Cold"],
    Options_Korean_Mean: ["맛을 보다", "느끼다", "덥다", "춥다"],
    Correct_Answer: "Taste",
    Correct_Answer_Korean_Mean: "맛을 보다",
  },
  {
    English_Word: "Feel",
    Korean_Mean: "느끼다",
    Options: ["Taste", "Feel", "Hot", "Cold"],
    Options_Korean_Mean: ["맛을 보다", "느끼다", "덥다", "춥다"],
    Correct_Answer: "Feel",
    Correct_Answer_Korean_Mean: "느끼다",
  },
  {
    English_Word: "Hot",
    Korean_Mean: "덥다",
    Options: ["Taste", "Feel", "Hot", "Cold"],
    Options_Korean_Mean: ["맛을 보다", "느끼다", "덥다", "춥다"],
    Correct_Answer: "Hot",
    Correct_Answer_Korean_Mean: "덥다",
  },
  {
    English_Word: "Cold",
    Korean_Mean: "춥다",
    Options: ["Taste", "Feel", "Hot", "Cold"],
    Options_Korean_Mean: ["맛을 보다", "느끼다", "덥다", "춥다"],
    Correct_Answer: "Cold",
    Correct_Answer_Korean_Mean: "춥다",
  },
  {
    English_Word: "Warm",
    Korean_Mean: "따뜻하다",
    Options: ["Warm", "Cool", "Beautiful", "Ugly"],
    Options_Korean_Mean: ["따뜻하다", "시원하다", "아름답다", "추하다"],
    Correct_Answer: "Warm",
    Correct_Answer_Korean_Mean: "따뜻하다",
  },
  {
    English_Word: "Cool",
    Korean_Mean: "시원하다",
    Options: ["Warm", "Cool", "Beautiful", "Ugly"],
    Options_Korean_Mean: ["따뜻하다", "시원하다", "아름답다", "추하다"],
    Correct_Answer: "Cool",
    Correct_Answer_Korean_Mean: "시원하다",
  },
  {
    English_Word: "Beautiful",
    Korean_Mean: "아름답다",
    Options: ["Warm", "Cool", "Beautiful", "Ugly"],
    Options_Korean_Mean: ["따뜻하다", "시원하다", "아름답다", "추하다"],
    Correct_Answer: "Beautiful",
    Correct_Answer_Korean_Mean: "아름답다",
  },
  {
    English_Word: "Ugly",
    Korean_Mean: "추하다",
    Options: ["Warm", "Cool", "Beautiful", "Ugly"],
    Options_Korean_Mean: ["따뜻하다", "시원하다", "아름답다", "추하다"],
    Correct_Answer: "Ugly",
    Correct_Answer_Korean_Mean: "추하다",
  },
  {
    English_Word: "Clean",
    Korean_Mean: "깨끗하다",
    Options: ["Clean", "Dirty", "Fast", "Slow"],
    Options_Korean_Mean: ["깨끗하다", "더럽다", "빠르다", "느리다"],
    Correct_Answer: "Clean",
    Correct_Answer_Korean_Mean: "깨끗하다",
  },
  {
    English_Word: "Dirty",
    Korean_Mean: "더럽다",
    Options: ["Clean", "Dirty", "Fast", "Slow"],
    Options_Korean_Mean: ["깨끗하다", "더럽다", "빠르다", "느리다"],
    Correct_Answer: "Dirty",
    Correct_Answer_Korean_Mean: "더럽다",
  },
  {
    English_Word: "Fast",
    Korean_Mean: "빠르다",
    Options: ["Clean", "Dirty", "Fast", "Slow"],
    Options_Korean_Mean: ["깨끗하다", "더럽다", "빠르다", "느리다"],
    Correct_Answer: "Fast",
    Correct_Answer_Korean_Mean: "빠르다",
  },
  {
    English_Word: "Slow",
    Korean_Mean: "느리다",
    Options: ["Clean", "Dirty", "Fast", "Slow"],
    Options_Korean_Mean: ["깨끗하다", "더럽다", "빠르다", "느리다"],
    Correct_Answer: "Slow",
    Correct_Answer_Korean_Mean: "느리다",
  },
  {
    English_Word: "Old",
    Korean_Mean: "늙다",
    Options: ["Old", "New", "Young", "Sky"],
    Options_Korean_Mean: ["늙다", "새로운", "젊다", "영재"],
    Correct_Answer: "Old",
    Correct_Answer_Korean_Mean: "늙다",
  },
  {
    English_Word: "New",
    Korean_Mean: "새로운",
    Options: ["Old", "New", "Young", "Red"],
    Options_Korean_Mean: ["마약", "새로운", "젊다", "늙다"],
    Correct_Answer: "New",
    Correct_Answer_Korean_Mean: "새로운",
  },
  {
    English_Word: "Young",
    Korean_Mean: "젊다",
    Options: ["Sky", "New", "Young", "Old"],
    Options_Korean_Mean: ["비밀", "새로운", "젊다", "늙다"],
    Correct_Answer: "Young",
    Correct_Answer_Korean_Mean: "젊다",
  },
  {
    English_Word: "Right",
    Korean_Mean: "옳다",
    Options: ["Right", "Wrong", "True", "False"],
    Options_Korean_Mean: ["옳다", "틀리다", "참된", "거짓의"],
    Correct_Answer: "Right",
    Correct_Answer_Korean_Mean: "옳다",
  },
  {
    English_Word: "Wrong",
    Korean_Mean: "틀리다",
    Options: ["Right", "Wrong", "True", "False"],
    Options_Korean_Mean: ["옳다", "틀리다", "참된", "거짓의"],
    Correct_Answer: "Wrong",
    Correct_Answer_Korean_Mean: "틀리다",
  },
  {
    English_Word: "True",
    Korean_Mean: "참된",
    Options: ["Right", "Wrong", "True", "False"],
    Options_Korean_Mean: ["옳다", "틀리다", "참된", "거짓의"],
    Correct_Answer: "True",
    Correct_Answer_Korean_Mean: "참된",
  },
  {
    English_Word: "False",
    Korean_Mean: "거짓의",
    Options: ["Right", "Wrong", "True", "False"],
    Options_Korean_Mean: ["옳다", "틀리다", "참된", "거짓의"],
    Correct_Answer: "False",
    Correct_Answer_Korean_Mean: "거짓의",
  },
];
