export const oxDay3 = [
  {
    English_Word: "Sad",
    Korean_Mean: "슬픈",
    Options: ["Sad", "Angry", "Excited", "Bored"],
    Options_Korean_Mean: ["슬픈", "화난", "흥분한", "지루한"],
    Correct_Answer: "Sad",
    Correct_Answer_Korean_Mean: "슬픈",
  },
  {
    English_Word: "Angry",
    Korean_Mean: "화난",
    Options: ["Sad", "Angry", "Excited", "Bored"],
    Options_Korean_Mean: ["슬픈", "화난", "흥분한", "지루한"],
    Correct_Answer: "Angry",
    Correct_Answer_Korean_Mean: "화난",
  },
  {
    English_Word: "Excited",
    Korean_Mean: "흥분한",
    Options: ["Sad", "Angry", "Excited", "Bored"],
    Options_Korean_Mean: ["슬픈", "화난", "흥분한", "지루한"],
    Correct_Answer: "Excited",
    Correct_Answer_Korean_Mean: "흥분한",
  },
  {
    English_Word: "Bored",
    Korean_Mean: "지루한",
    Options: ["Sad", "Angry", "Excited", "Bored"],
    Options_Korean_Mean: ["슬픈", "화난", "흥분한", "지루한"],
    Correct_Answer: "Bored",
    Correct_Answer_Korean_Mean: "지루한",
  },
  {
    English_Word: "Tired",
    Korean_Mean: "피곤한",
    Options: ["Tired", "Energetic", "Quiet", "Loud"],
    Options_Korean_Mean: ["피곤한", "활기찬", "조용한", "시끄러운"],
    Correct_Answer: "Tired",
    Correct_Answer_Korean_Mean: "피곤한",
  },
  {
    English_Word: "Energetic",
    Korean_Mean: "활기찬",
    Options: ["Tired", "Energetic", "Quiet", "Loud"],
    Options_Korean_Mean: ["피곤한", "활기찬", "조용한", "시끄러운"],
    Correct_Answer: "Energetic",
    Correct_Answer_Korean_Mean: "활기찬",
  },
  {
    English_Word: "Quiet",
    Korean_Mean: "조용한",
    Options: ["Tired", "Energetic", "Quiet", "Loud"],
    Options_Korean_Mean: ["피곤한", "활기찬", "조용한", "시끄러운"],
    Correct_Answer: "Quiet",
    Correct_Answer_Korean_Mean: "조용한",
  },
  {
    English_Word: "Loud",
    Korean_Mean: "시끄러운",
    Options: ["Tired", "Energetic", "Quiet", "Loud"],
    Options_Korean_Mean: ["피곤한", "활기찬", "조용한", "시끄러운"],
    Correct_Answer: "Loud",
    Correct_Answer_Korean_Mean: "시끄러운",
  },
  {
    English_Word: "Soft",
    Korean_Mean: "부드러운",
    Options: ["Soft", "Hard", "Easy", "Difficult"],
    Options_Korean_Mean: ["부드러운", "딱딱한", "쉬운", "어려운"],
    Correct_Answer: "Soft",
    Correct_Answer_Korean_Mean: "부드러운",
  },
  {
    English_Word: "Hard",
    Korean_Mean: "딱딱한",
    Options: ["Soft", "Hard", "Easy", "Difficult"],
    Options_Korean_Mean: ["부드러운", "딱딱한", "쉬운", "어려운"],
    Correct_Answer: "Hard",
    Correct_Answer_Korean_Mean: "딱딱한",
  },
  {
    English_Word: "Easy",
    Korean_Mean: "쉬운",
    Options: ["Soft", "Hard", "Easy", "Difficult"],
    Options_Korean_Mean: ["부드러운", "딱딱한", "쉬운", "어려운"],
    Correct_Answer: "Easy",
    Correct_Answer_Korean_Mean: "쉬운",
  },
  {
    English_Word: "Difficult",
    Korean_Mean: "어려운",
    Options: ["Soft", "Hard", "Easy", "Difficult"],
    Options_Korean_Mean: ["부드러운", "딱딱한", "쉬운", "어려운"],
    Correct_Answer: "Difficult",
    Correct_Answer_Korean_Mean: "어려운",
  },
  {
    English_Word: "Simple",
    Korean_Mean: "간단한",
    Options: ["Simple", "Complex", "Open", "Closed"],
    Options_Korean_Mean: ["간단한", "복잡한", "열린", "닫힌"],
    Correct_Answer: "Simple",
    Correct_Answer_Korean_Mean: "간단한",
  },
  {
    English_Word: "Complex",
    Korean_Mean: "복잡한",
    Options: ["Simple", "Complex", "Open", "Closed"],
    Options_Korean_Mean: ["간단한", "복잡한", "열린", "닫힌"],
    Correct_Answer: "Complex",
    Correct_Answer_Korean_Mean: "복잡한",
  },
  {
    English_Word: "Open",
    Korean_Mean: "열린",
    Options: ["Simple", "Complex", "Open", "Closed"],
    Options_Korean_Mean: ["간단한", "복잡한", "열린", "닫힌"],
    Correct_Answer: "Open",
    Correct_Answer_Korean_Mean: "열린",
  },
  {
    English_Word: "Closed",
    Korean_Mean: "닫힌",
    Options: ["Simple", "Complex", "Open", "Closed"],
    Options_Korean_Mean: ["간단한", "복잡한", "열린", "닫힌"],
    Correct_Answer: "Closed",
    Correct_Answer_Korean_Mean: "닫힌",
  },
  {
    English_Word: "Free",
    Korean_Mean: "자유로운",
    Options: ["Free", "Expensive", "Cheap", "Rich"],
    Options_Korean_Mean: ["자유로운", "비싼", "싸구려한", "부자의"],
    Correct_Answer: "Free",
    Correct_Answer_Korean_Mean: "자유로운",
  },
  {
    English_Word: "Expensive",
    Korean_Mean: "비싼",
    Options: ["Free", "Expensive", "Cheap", "Rich"],
    Options_Korean_Mean: ["자유로운", "비싼", "싸구려한", "부자의"],
    Correct_Answer: "Expensive",
    Correct_Answer_Korean_Mean: "비싼",
  },
  {
    English_Word: "Cheap",
    Korean_Mean: "싸구려한",
    Options: ["Free", "Expensive", "Cheap", "Rich"],
    Options_Korean_Mean: ["자유로운", "비싼", "싸구려한", "부자의"],
    Correct_Answer: "Cheap",
    Correct_Answer_Korean_Mean: "싸구려한",
  },
  {
    English_Word: "Rich",
    Korean_Mean: "부자의",
    Options: ["Free", "Expensive", "Cheap", "Rich"],
    Options_Korean_Mean: ["자유로운", "비싼", "싸구려한", "부자의"],
    Correct_Answer: "Rich",
    Correct_Answer_Korean_Mean: "부자의",
  },
  {
    English_Word: "Poor",
    Korean_Mean: "가난한",
    Options: ["Poor", "Big", "Small", "Long"],
    Options_Korean_Mean: ["가난한", "큰", "작은", "긴"],
    Correct_Answer: "Poor",
    Correct_Answer_Korean_Mean: "가난한",
  },
  {
    English_Word: "Big",
    Korean_Mean: "큰",
    Options: ["Poor", "Big", "Small", "Long"],
    Options_Korean_Mean: ["가난한", "큰", "작은", "긴"],
    Correct_Answer: "Big",
    Correct_Answer_Korean_Mean: "큰",
  },
  {
    English_Word: "Small",
    Korean_Mean: "작은",
    Options: ["Poor", "Big", "Small", "Long"],
    Options_Korean_Mean: ["가난한", "큰", "작은", "긴"],
    Correct_Answer: "Small",
    Correct_Answer_Korean_Mean: "작은",
  },
  {
    English_Word: "Long",
    Korean_Mean: "긴",
    Options: ["Poor", "Big", "Small", "Long"],
    Options_Korean_Mean: ["가난한", "큰", "작은", "긴"],
    Correct_Answer: "Long",
    Correct_Answer_Korean_Mean: "긴",
  },
  {
    English_Word: "Short",
    Korean_Mean: "짧은",
    Options: ["Hot", "Cold", "Warm", "Short"],
    Options_Korean_Mean: ["덥고", "춥고", "따뜻한", "짧은"],
    Correct_Answer: "Short",
    Correct_Answer_Korean_Mean: "짧은",
  },
  {
    English_Word: "Tall",
    Korean_Mean: "키가 큰",
    Options: ["Tall", "Short", "Heavy", "Light"],
    Options_Korean_Mean: ["키가 큰", "키가 작은", "무거운", "가벼운"],
    Correct_Answer: "Tall",
    Correct_Answer_Korean_Mean: "키가 큰",
  },
  {
    English_Word: "Short",
    Korean_Mean: "키가 작은",
    Options: ["Tall", "Short", "Heavy", "Light"],
    Options_Korean_Mean: ["키가 큰", "키가 작은", "무거운", "가벼운"],
    Correct_Answer: "Short",
    Correct_Answer_Korean_Mean: "키가 작은",
  },
  {
    English_Word: "Heavy",
    Korean_Mean: "무거운",
    Options: ["Tall", "Short", "Heavy", "Light"],
    Options_Korean_Mean: ["키가 큰", "키가 작은", "무거운", "가벼운"],
    Correct_Answer: "Heavy",
    Correct_Answer_Korean_Mean: "무거운",
  },
  {
    English_Word: "Light",
    Korean_Mean: "가벼운",
    Options: ["Tall", "Short", "Heavy", "Light"],
    Options_Korean_Mean: ["키가 큰", "키가 작은", "무거운", "가벼운"],
    Correct_Answer: "Light",
    Correct_Answer_Korean_Mean: "가벼운",
  },
  {
    English_Word: "Deep",
    Korean_Mean: "깊은",
    Options: ["Deep", "Shallow", "Wide", "Narrow"],
    Options_Korean_Mean: ["깊은", "얕은", "넓은", "좁은"],
    Correct_Answer: "Deep",
    Correct_Answer_Korean_Mean: "깊은",
  },
  {
    English_Word: "Shallow",
    Korean_Mean: "얕은",
    Options: ["Deep", "Shallow", "Wide", "Narrow"],
    Options_Korean_Mean: ["깊은", "얕은", "넓은", "좁은"],
    Correct_Answer: "Shallow",
    Correct_Answer_Korean_Mean: "얕은",
  },
  {
    English_Word: "Wide",
    Korean_Mean: "넓은",
    Options: ["Deep", "Shallow", "Wide", "Narrow"],
    Options_Korean_Mean: ["깊은", "얕은", "넓은", "좁은"],
    Correct_Answer: "Wide",
    Correct_Answer_Korean_Mean: "넓은",
  },
  {
    English_Word: "Narrow",
    Korean_Mean: "좁은",
    Options: ["Deep", "Shallow", "Wide", "Narrow"],
    Options_Korean_Mean: ["깊은", "얕은", "넓은", "좁은"],
    Correct_Answer: "Narrow",
    Correct_Answer_Korean_Mean: "좁은",
  },
  {
    English_Word: "Far",
    Korean_Mean: "멀리",
    Options: ["Far", "Near", "Day", "Night"],
    Options_Korean_Mean: ["멀리", "가까이", "낮", "밤"],
    Correct_Answer: "Far",
    Correct_Answer_Korean_Mean: "멀리",
  },
  {
    English_Word: "Near",
    Korean_Mean: "가까이",
    Options: ["Far", "Near", "Day", "Night"],
    Options_Korean_Mean: ["멀리", "가까이", "낮", "밤"],
    Correct_Answer: "Near",
    Correct_Answer_Korean_Mean: "가까이",
  },
  {
    English_Word: "Day",
    Korean_Mean: "낮",
    Options: ["Day", "Night", "Morning", "Afternoon"],
    Options_Korean_Mean: ["낮", "밤", "아침", "오후"],
    Correct_Answer: "Day",
    Correct_Answer_Korean_Mean: "낮",
  },
  {
    English_Word: "Night",
    Korean_Mean: "밤",
    Options: ["Day", "Night", "Morning", "Afternoon"],
    Options_Korean_Mean: ["낮", "밤", "아침", "오후"],
    Correct_Answer: "Night",
    Correct_Answer_Korean_Mean: "밤",
  },
  {
    English_Word: "Morning",
    Korean_Mean: "아침",
    Options: ["Day", "Night", "Morning", "Afternoon"],
    Options_Korean_Mean: ["낮", "밤", "아침", "오후"],
    Correct_Answer: "Morning",
    Correct_Answer_Korean_Mean: "아침",
  },
  {
    English_Word: "Afternoon",
    Korean_Mean: "오후",
    Options: ["Day", "Night", "Morning", "Afternoon"],
    Options_Korean_Mean: ["낮", "밤", "아침", "오후"],
    Correct_Answer: "Afternoon",
    Correct_Answer_Korean_Mean: "오후",
  },
  {
    English_Word: "Evening",
    Korean_Mean: "저녁",
    Options: ["Evening", "Today", "Yesterday", "Tomorrow"],
    Options_Korean_Mean: ["저녁", "오늘", "어제", "내일"],
    Correct_Answer: "Evening",
    Correct_Answer_Korean_Mean: "저녁",
  },
  {
    English_Word: "Today",
    Korean_Mean: "오늘",
    Options: ["Evening", "Today", "Yesterday", "Tomorrow"],
    Options_Korean_Mean: ["저녁", "오늘", "어제", "내일"],
    Correct_Answer: "Today",
    Correct_Answer_Korean_Mean: "오늘",
  },
  {
    English_Word: "Yesterday",
    Korean_Mean: "어제",
    Options: ["Evening", "Today", "Yesterday", "Tomorrow"],
    Options_Korean_Mean: ["저녁", "오늘", "어제", "내일"],
    Correct_Answer: "Yesterday",
    Correct_Answer_Korean_Mean: "어제",
  },
  {
    English_Word: "Tomorrow",
    Korean_Mean: "내일",
    Options: ["Evening", "Today", "Yesterday", "Tomorrow"],
    Options_Korean_Mean: ["저녁", "오늘", "어제", "내일"],
    Correct_Answer: "Tomorrow",
    Correct_Answer_Korean_Mean: "내일",
  },
  {
    English_Word: "Week",
    Korean_Mean: "주",
    Options: ["Week", "Month", "Year", "Minute"],
    Options_Korean_Mean: ["주", "월", "년", "분"],
    Correct_Answer: "Week",
    Correct_Answer_Korean_Mean: "주",
  },
  {
    English_Word: "Month",
    Korean_Mean: "월",
    Options: ["Week", "Month", "Year", "Minute"],
    Options_Korean_Mean: ["주", "월", "년", "분"],
    Correct_Answer: "Month",
    Correct_Answer_Korean_Mean: "월",
  },
  {
    English_Word: "Year",
    Korean_Mean: "년",
    Options: ["Week", "Month", "Year", "Minute"],
    Options_Korean_Mean: ["주", "월", "년", "분"],
    Correct_Answer: "Year",
    Correct_Answer_Korean_Mean: "년",
  },
  {
    English_Word: "Minute",
    Korean_Mean: "분",
    Options: ["Week", "Month", "Year", "Minute"],
    Options_Korean_Mean: ["주", "월", "년", "분"],
    Correct_Answer: "Minute",
    Correct_Answer_Korean_Mean: "분",
  },
  {
    English_Word: "Second",
    Korean_Mean: "초",
    Options: ["Day", "Night", "Morning", "Second"],
    Options_Korean_Mean: ["낮", "밤", "아침", "초"],
    Correct_Answer: "Second",
    Correct_Answer_Korean_Mean: "초",
  },
  {
    English_Word: "Hour",
    Korean_Mean: "시간",
    Options: ["Hour", "Minute", "Second", "Day"],
    Options_Korean_Mean: ["시간", "분", "초", "낮"],
    Correct_Answer: "Hour",
    Correct_Answer_Korean_Mean: "시간",
  },
];
