export const oxDay4 = [
  {
    English_Word: "Clock",
    Korean_Mean: "시계",
    Options: ["Clock", "Calendar", "Sun", "Moon"],
    Options_Korean_Mean: ["시계", "달력", "태양", "달"],
    Correct_Answer: "Clock",
    Correct_Answer_Korean_Mean: "시계",
  },
  {
    English_Word: "Watch",
    Korean_Mean: "손목시계",
    Options: ["Calendar", "Sun", "Watch", "Star"],
    Options_Korean_Mean: ["달력", "손목시계", "달", "별"],
    Correct_Answer: "Watch",
    Correct_Answer_Korean_Mean: "손목시계",
  },
  {
    English_Word: "Calendar",
    Korean_Mean: "달력",
    Options: ["Sun", "Moon", "Calendar", "Sky"],
    Options_Korean_Mean: ["태양", "달", "달력", "하늘"],
    Correct_Answer: "Calendar",
    Correct_Answer_Korean_Mean: "달력",
  },
  {
    English_Word: "Sun",
    Korean_Mean: "태양",
    Options: ["Moon", "Star", "Sun", "Cloud"],
    Options_Korean_Mean: ["달", "별", "하늘", "태양"],
    Correct_Answer: "Sun",
    Correct_Answer_Korean_Mean: "태양",
  },
  {
    English_Word: "Moon",
    Korean_Mean: "달",
    Options: ["Moon", "Sky", "Cloud", "Rain"],
    Options_Korean_Mean: ["달", "하늘", "구름", "비"],
    Correct_Answer: "Moon",
    Correct_Answer_Korean_Mean: "달",
  },
  {
    English_Word: "Star",
    Korean_Mean: "별",
    Options: ["Sky", "Cloud", "Star", "Snow"],
    Options_Korean_Mean: ["하늘", "구름", "별", "눈"],
    Correct_Answer: "Star",
    Correct_Answer_Korean_Mean: "별",
  },
  {
    English_Word: "Sky",
    Korean_Mean: "하늘",
    Options: ["Cloud", "Rain", "Sky", "Wind"],
    Options_Korean_Mean: ["구름", "비", "눈", "하늘"],
    Correct_Answer: "Sky",
    Correct_Answer_Korean_Mean: "하늘",
  },
  {
    English_Word: "Cloud",
    Korean_Mean: "구름",
    Options: ["Cloud", "Snow", "Wind", "Storm"],
    Options_Korean_Mean: ["비", "눈", "구름", "폭풍"],
    Correct_Answer: "Cloud",
    Correct_Answer_Korean_Mean: "구름",
  },
  {
    English_Word: "Rain",
    Korean_Mean: "비",
    Options: ["Snow", "Rain", "Storm", "Thunder"],
    Options_Korean_Mean: ["눈", "바람", "비", "천둥"],
    Correct_Answer: "Rain",
    Correct_Answer_Korean_Mean: "비",
  },
  {
    English_Word: "Snow",
    Korean_Mean: "눈",
    Options: ["Snow", "Storm", "Thunder", "Lightning"],
    Options_Korean_Mean: ["바람", "폭풍", "눈", "번개"],
    Correct_Answer: "Snow",
    Correct_Answer_Korean_Mean: "눈",
  },
  {
    English_Word: "Wind",
    Korean_Mean: "바람",
    Options: ["Storm", "Thunder", "Wind", "Fire"],
    Options_Korean_Mean: ["폭풍", "바람", "번개", "불"],
    Correct_Answer: "Wind",
    Correct_Answer_Korean_Mean: "바람",
  },
  {
    English_Word: "Storm",
    Korean_Mean: "폭풍",
    Options: ["Thunder", "Storm", "Fire", "Water"],
    Options_Korean_Mean: ["천둥", "번개", "불", "폭풍"],
    Correct_Answer: "Storm",
    Correct_Answer_Korean_Mean: "폭풍",
  },
  {
    English_Word: "Thunder",
    Korean_Mean: "천둥",
    Options: ["Thunder", "Fire", "Water", "Ice"],
    Options_Korean_Mean: ["번개", "천둥", "물", "얼음"],
    Correct_Answer: "Thunder",
    Correct_Answer_Korean_Mean: "천둥",
  },
  {
    English_Word: "Lightning",
    Korean_Mean: "번개",
    Options: ["Fire", "Water", "Ice", "Lightning"],
    Options_Korean_Mean: ["불", "물", "번개", "공기"],
    Correct_Answer: "Lightning",
    Correct_Answer_Korean_Mean: "번개",
  },
  {
    English_Word: "Fire",
    Korean_Mean: "불",
    Options: ["Fire", "Ice", "Air", "Earth"],
    Options_Korean_Mean: ["물", "얼음", "공기", "불"],
    Correct_Answer: "Fire",
    Correct_Answer_Korean_Mean: "불",
  },
  {
    English_Word: "Water",
    Korean_Mean: "물",
    Options: ["Ice", "Air", "Earth", "Water"],
    Options_Korean_Mean: ["얼음", "공기", "물", "지면"],
    Correct_Answer: "Water",
    Correct_Answer_Korean_Mean: "물",
  },
  {
    English_Word: "Ice",
    Korean_Mean: "얼음",
    Options: ["Air", "Earth", "Ice", "Sea"],
    Options_Korean_Mean: ["공기", "땅", "얼음", "바다"],
    Correct_Answer: "Ice",
    Correct_Answer_Korean_Mean: "얼음",
  },
  {
    English_Word: "Air",
    Korean_Mean: "공기",
    Options: ["Air", "Land", "Sea", "Mountain"],
    Options_Korean_Mean: ["땅", "지면", "바다", "공기"],
    Correct_Answer: "Air",
    Correct_Answer_Korean_Mean: "공기",
  },
  {
    English_Word: "Earth",
    Korean_Mean: "땅",
    Options: ["Earth", "Sea", "Mountain", "Valley"],
    Options_Korean_Mean: ["지면", "바다", "땅", "계곡"],
    Correct_Answer: "Earth",
    Correct_Answer_Korean_Mean: "땅",
  },
  {
    English_Word: "Land",
    Korean_Mean: "지면",
    Options: ["Sea", "Land", "Valley", "Forest"],
    Options_Korean_Mean: ["바다", "산", "계곡", "지면"],
    Correct_Answer: "Land",
    Correct_Answer_Korean_Mean: "지면",
  },
  {
    English_Word: "Sea",
    Korean_Mean: "바다",
    Options: ["Mountain", "Valley", "Forest", "Sea"],
    Options_Korean_Mean: ["산", "바다", "숲", "사막"],
    Correct_Answer: "Sea",
    Correct_Answer_Korean_Mean: "바다",
  },
  {
    English_Word: "Mountain",
    Korean_Mean: "산",
    Options: ["Valley", "Mountain", "Desert", "Beach"],
    Options_Korean_Mean: ["계곡", "숲", "산", "해변"],
    Correct_Answer: "Mountain",
    Correct_Answer_Korean_Mean: "산",
  },
  {
    English_Word: "Valley",
    Korean_Mean: "계곡",
    Options: ["Forest", "Desert", "Beach", "Valley"],
    Options_Korean_Mean: ["계곡", "사막", "해변", "강"],
    Correct_Answer: "Valley",
    Correct_Answer_Korean_Mean: "계곡",
  },
  {
    English_Word: "Forest",
    Korean_Mean: "숲",
    Options: ["Desert", "Beach", "Forest", "Lake"],
    Options_Korean_Mean: ["사막", "해변", "강", "숲"],
    Correct_Answer: "Forest",
    Correct_Answer_Korean_Mean: "숲",
  },
  {
    English_Word: "Desert",
    Korean_Mean: "사막",
    Options: ["Beach", "River", "Lake", "Desert"],
    Options_Korean_Mean: ["사막", "강", "호수", "연못"],
    Correct_Answer: "Desert",
    Correct_Answer_Korean_Mean: "사막",
  },
  {
    English_Word: "Beach",
    Korean_Mean: "해변",
    Options: ["River", "Lake", "Pond", "Beach"],
    Options_Korean_Mean: ["강", "해변", "연못", "대양"],
    Correct_Answer: "Beach",
    Correct_Answer_Korean_Mean: "해변",
  },
  {
    English_Word: "River",
    Korean_Mean: "강",
    Options: ["Lake", "Pond", "Ocean", "Island"],
    Options_Korean_Mean: ["호수", "River", "강", "섬"],
    Correct_Answer: "River",
    Correct_Answer_Korean_Mean: "강",
  },
  {
    English_Word: "Lake",
    Korean_Mean: "호수",
    Options: ["Pond", "Ocean", "Lake", "Continent"],
    Options_Korean_Mean: ["연못", "호수", "섬", "대륙"],
    Correct_Answer: "Lake",
    Correct_Answer_Korean_Mean: "호수",
  },
  {
    English_Word: "Pond",
    Korean_Mean: "연못",
    Options: ["Pond", "Island", "Continent", "Country"],
    Options_Korean_Mean: ["대양", "섬", "대륙", "연못"],
    Correct_Answer: "Pond",
    Correct_Answer_Korean_Mean: "연못",
  },
  {
    English_Word: "Ocean",
    Korean_Mean: "대양",
    Options: ["Island", "Continent", "Ocean", "City"],
    Options_Korean_Mean: ["섬", "대륙", "국가", "대양"],
    Correct_Answer: "Ocean",
    Correct_Answer_Korean_Mean: "대양",
  },
  {
    English_Word: "Island",
    Korean_Mean: "섬",
    Options: ["Island", "Country", "City", "Town"],
    Options_Korean_Mean: ["대륙", "국가", "섬", "마을"],
    Correct_Answer: "Island",
    Correct_Answer_Korean_Mean: "섬",
  },
  {
    English_Word: "Continent",
    Korean_Mean: "대륙",
    Options: ["Country", "Continent", "Town", "Village"],
    Options_Korean_Mean: ["국가", "도시", "마을", "대륙"],
    Correct_Answer: "Continent",
    Correct_Answer_Korean_Mean: "대륙",
  },
  {
    English_Word: "Country",
    Korean_Mean: "국가",
    Options: ["Country", "Town", "Village", "Street"],
    Options_Korean_Mean: ["도시", "국가", "마을", "거리"],
    Correct_Answer: "Country",
    Correct_Answer_Korean_Mean: "국가",
  },
  {
    English_Word: "City",
    Korean_Mean: "도시",
    Options: ["Town", "Village", "Street", "City"],
    Options_Korean_Mean: ["마을", "행인", "거리", "도시"],
    Correct_Answer: "City",
    Correct_Answer_Korean_Mean: "도시",
  },
  {
    English_Word: "Town",
    Korean_Mean: "마을",
    Options: ["Village", "Town", "Road", "Highway"],
    Options_Korean_Mean: ["마을", "거리", "길", "고속도로"],
    Correct_Answer: "Town",
    Correct_Answer_Korean_Mean: "마을",
  },
  {
    English_Word: "Village",
    Korean_Mean: "마을",
    Options: ["Street", "Road", "Highway", "Village"],
    Options_Korean_Mean: ["거리", "길", "마을", "다리"],
    Correct_Answer: "Village",
    Correct_Answer_Korean_Mean: "마을",
  },
  {
    English_Word: "Street",
    Korean_Mean: "거리",
    Options: ["Road", "Highway", "Bridge", "Street"],
    Options_Korean_Mean: ["길", "고속도로", "거리", "터널"],
    Correct_Answer: "Street",
    Correct_Answer_Korean_Mean: "거리",
  },
  {
    English_Word: "Road",
    Korean_Mean: "길",
    Options: ["Highway", "Road", "Tunnel", "Building"],
    Options_Korean_Mean: ["길", "다리", "터널", "건물"],
    Correct_Answer: "Road",
    Correct_Answer_Korean_Mean: "길",
  },
  {
    English_Word: "Highway",
    Korean_Mean: "고속도로",
    Options: ["Bridge", "Tunnel", "Highway", "House"],
    Options_Korean_Mean: ["다리", "터널", "고속도로", "집"],
    Correct_Answer: "Highway",
    Correct_Answer_Korean_Mean: "고속도로",
  },
  {
    English_Word: "Bridge",
    Korean_Mean: "다리",
    Options: ["Tunnel", "Building", "Bridge", "Apartment"],
    Options_Korean_Mean: ["다리", "건물", "집", "아파트"],
    Correct_Answer: "Bridge",
    Correct_Answer_Korean_Mean: "다리",
  },
  {
    English_Word: "Tunnel",
    Korean_Mean: "터널",
    Options: ["Building", "House", "Apartment", "Tunnel"],
    Options_Korean_Mean: ["건물", "집", "아파트", "터널"],
    Correct_Answer: "Tunnel",
    Correct_Answer_Korean_Mean: "터널",
  },
  {
    English_Word: "Building",
    Korean_Mean: "건물",
    Options: ["House", "Building", "Room", "Kitchen"],
    Options_Korean_Mean: ["건물", "아파트", "방", "주방"],
    Correct_Answer: "Building",
    Correct_Answer_Korean_Mean: "건물",
  },
  {
    English_Word: "House",
    Korean_Mean: "집",
    Options: ["House", "Room", "Kitchen", "Bathroom"],
    Options_Korean_Mean: ["아파트", "집", "주방", "화장실"],
    Correct_Answer: "House",
    Correct_Answer_Korean_Mean: "집",
  },
  {
    English_Word: "Apartment",
    Korean_Mean: "아파트",
    Options: ["Room", "Kitchen", "Bathroom", "Apartment"],
    Options_Korean_Mean: ["방", "주방", "화장실", "아파트"],
    Correct_Answer: "Apartment",
    Correct_Answer_Korean_Mean: "아파트",
  },
  {
    English_Word: "Room",
    Korean_Mean: "방",
    Options: ["Kitchen", "Bathroom", "Room", "Living room"],
    Options_Korean_Mean: ["방", "화장실", "침실", "거실"],
    Correct_Answer: "Room",
    Correct_Answer_Korean_Mean: "방",
  },
  {
    English_Word: "Kitchen",
    Korean_Mean: "주방",
    Options: ["Bathroom", "Bedroom", "Living room", "Kitchen"],
    Options_Korean_Mean: ["주방", "침실", "거실", "거리"],
    Correct_Answer: "Kitchen",
    Correct_Answer_Korean_Mean: "주방",
  },
  {
    English_Word: "Bathroom",
    Korean_Mean: "화장실",
    Options: ["Bedroom", "Living room", "Bathroom", "Road"],
    Options_Korean_Mean: ["침실", "화장실", "거리", "길"],
    Correct_Answer: "Bathroom",
    Correct_Answer_Korean_Mean: "화장실",
  },
  {
    English_Word: "Bedroom",
    Korean_Mean: "침실",
    Options: ["Living room", "Bedroom", "Road", "Highway"],
    Options_Korean_Mean: ["거실", "침실", "길", "고속도로"],
    Correct_Answer: "Bedroom",
    Correct_Answer_Korean_Mean: "침실",
  },
  {
    English_Word: "Living room",
    Korean_Mean: "거실",
    Options: ["Street", "Living room", "Highway", "Bridge"],
    Options_Korean_Mean: ["거리", "길", "거실", "다리"],
    Correct_Answer: "Living room",
    Correct_Answer_Korean_Mean: "거실",
  },
  // ... Continue this pattern for the remaining words ...
];
