export const oxDay5 = [
  {
    English_Word: "Office",
    Korean_Mean: "사무실",
    Options: ["Home", "School", "Office", "Library"],
    Options_Korean_Mean: ["집", "학교", "사무실", "도서관"],
    Correct_Answer: "Office",
    Correct_Answer_Korean_Mean: "사무실",
  },
  {
    English_Word: "School",
    Korean_Mean: "학교",
    Options: ["Office", "University", "School", "Library"],
    Options_Korean_Mean: ["사무실", "학교", "교실", "도서관"],
    Correct_Answer: "School",
    Correct_Answer_Korean_Mean: "학교",
  },
  {
    English_Word: "University",
    Korean_Mean: "대학",
    Options: ["University", "School", "Library", "Hospital"],
    Options_Korean_Mean: ["대학", "학교", "도서관", "병원"],
    Correct_Answer: "University",
    Correct_Answer_Korean_Mean: "대학",
  },
  {
    English_Word: "College",
    Korean_Mean: "대학교",
    Options: ["University", "College", "Library", "Hospital"],
    Options_Korean_Mean: ["대학생", "교실", "도서관", "대학교"],
    Correct_Answer: "College",
    Correct_Answer_Korean_Mean: "대학교",
  },
  {
    English_Word: "Classroom",
    Korean_Mean: "교실",
    Options: ["Library", "School", "Office", "Classroom"],
    Options_Korean_Mean: ["도서관", "교실", "사무실", "병원"],
    Correct_Answer: "Classroom",
    Correct_Answer_Korean_Mean: "교실",
  },
  {
    English_Word: "Library",
    Korean_Mean: "도서관",
    Options: ["Bookstore", "Library", "Office", "Hospital"],
    Options_Korean_Mean: ["도서관", "교실", "사무실", "병원"],
    Correct_Answer: "Library",
    Correct_Answer_Korean_Mean: "도서관",
  },
  {
    English_Word: "Bookstore",
    Korean_Mean: "서점",
    Options: ["Library", "Hospital", "Office", "Bookstore"],
    Options_Korean_Mean: ["도서관", "병원", "사무실", "서점"],
    Correct_Answer: "Bookstore",
    Correct_Answer_Korean_Mean: "서점",
  },
  {
    English_Word: "Hospital",
    Korean_Mean: "병원",
    Options: ["Clinic", "University", "Hospital", "School"],
    Options_Korean_Mean: ["의원", "대학", "서점", "병원"],
    Correct_Answer: "Hospital",
    Correct_Answer_Korean_Mean: "병원",
  },
  {
    English_Word: "Clinic",
    Korean_Mean: "의원",
    Options: ["Hospital", "Doctor", "Clinic", "Patient"],
    Options_Korean_Mean: ["병원", "의원", "간호사", "환자"],
    Correct_Answer: "Clinic",
    Correct_Answer_Korean_Mean: "의원",
  },
  {
    English_Word: "Doctor",
    Korean_Mean: "의사",
    Options: ["Nurse", "Doctor", "Patient", "Medicine"],
    Options_Korean_Mean: ["의사", "의원", "환자", "약"],
    Correct_Answer: "Doctor",
    Correct_Answer_Korean_Mean: "의사",
  },
  {
    English_Word: "Nurse",
    Korean_Mean: "간호사",
    Options: ["Nurse", "Clinic", "Patient", "Medicine"],
    Options_Korean_Mean: ["의사", "간호사", "환자", "약"],
    Correct_Answer: "Nurse",
    Correct_Answer_Korean_Mean: "간호사",
  },
  {
    English_Word: "Patient",
    Korean_Mean: "환자",
    Options: ["Medicine", "Health", "Wellness", "Patient"],
    Options_Korean_Mean: ["약", "건강", "환자", "피트니스"],
    Correct_Answer: "Patient",
    Correct_Answer_Korean_Mean: "환자",
  },
  {
    English_Word: "Medicine",
    Korean_Mean: "약",
    Options: ["Health", "Medicine", "Fitness", "Exercise"],
    Options_Korean_Mean: ["건강", "웰니스", "약", "운동"],
    Correct_Answer: "Medicine",
    Correct_Answer_Korean_Mean: "약",
  },
  {
    English_Word: "Health",
    Korean_Mean: "건강",
    Options: ["Fitness", "Health", "Wellness", "Exercise"],
    Options_Korean_Mean: ["건강", "질병", "웰니스", "운동"],
    Correct_Answer: "Health",
    Correct_Answer_Korean_Mean: "건강",
  },
  {
    English_Word: "Wellness",
    Korean_Mean: "웰니스",
    Options: ["Wellness", "Sickness", "Health", "Exercise"],
    Options_Korean_Mean: ["웰니스", "질병", "건강", "운동"],
    Correct_Answer: "Wellness",
    Correct_Answer_Korean_Mean: "웰니스",
  },
  {
    English_Word: "Fitness",
    Korean_Mean: "피트니스",
    Options: ["Exercise", "Fitness", "Game", "Play"],
    Options_Korean_Mean: ["운동", "피트니스", "게임", "놀이"],
    Correct_Answer: "Fitness",
    Correct_Answer_Korean_Mean: "피트니스",
  },
  {
    English_Word: "Sport",
    Korean_Mean: "스포츠",
    Options: ["Sport", "Play", "Fun", "Entertainment"],
    Options_Korean_Mean: ["스포츠", "놀이", "즐거움", "엔터테인먼트"],
    Correct_Answer: "Sport",
    Correct_Answer_Korean_Mean: "스포츠",
  },
  {
    English_Word: "Game",
    Korean_Mean: "게임",
    Options: ["Play", "Fun", "Entertainment", "Game"],
    Options_Korean_Mean: ["놀이", "즐거움", "엔터테인먼트", "게임"],
    Correct_Answer: "Game",
    Correct_Answer_Korean_Mean: "게임",
  },
  {
    English_Word: "Play",
    Korean_Mean: "놀이",
    Options: ["Fun", "Entertainment", "Play", "Music"],
    Options_Korean_Mean: ["즐거움", "엔터테인먼트", "놀이", "음악"],
    Correct_Answer: "Play",
    Correct_Answer_Korean_Mean: "놀이",
  },
  {
    English_Word: "Fun",
    Korean_Mean: "즐거움",
    Options: ["Entertainment", "Fun", "Music", "Dance"],
    Options_Korean_Mean: ["엔터테인먼트", "즐거움", "음악", "춤"],
    Correct_Answer: "Fun",
    Correct_Answer_Korean_Mean: "즐거움",
  },
  {
    English_Word: "Entertainment",
    Korean_Mean: "엔터테인먼트",
    Options: ["Art", "Music", "Dance", "Entertainment"],
    Options_Korean_Mean: ["미술", "엔터테인먼트", "춤", "극장"],
    Correct_Answer: "Entertainment",
    Correct_Answer_Korean_Mean: "엔터테인먼트",
  },
  {
    English_Word: "Art",
    Korean_Mean: "미술",
    Options: ["Music", "Art", "Theater", "Film"],
    Options_Korean_Mean: ["음악", "춤", "미술", "영화"],
    Correct_Answer: "Art",
    Correct_Answer_Korean_Mean: "미술",
  },
  {
    English_Word: "Music",
    Korean_Mean: "음악",
    Options: ["Music", "Theater", "Film", "Television"],
    Options_Korean_Mean: ["춤", "음악", "영화", "텔레비전"],
    Correct_Answer: "Music",
    Correct_Answer_Korean_Mean: "음악",
  },
  {
    English_Word: "Dance",
    Korean_Mean: "춤",
    Options: ["Theater", "Film", "Television", "Dance"],
    Options_Korean_Mean: ["춤", "영화", "텔레비전", "라디오"],
    Correct_Answer: "Dance",
    Correct_Answer_Korean_Mean: "춤",
  },
  {
    English_Word: "Theater",
    Korean_Mean: "극장",
    Options: ["Film", "Television", "Theater", "Internet"],
    Options_Korean_Mean: ["영화", "극장", "라디오", "인터넷"],
    Correct_Answer: "Theater",
    Correct_Answer_Korean_Mean: "극장",
  },
  {
    English_Word: "Film",
    Korean_Mean: "영화",
    Options: ["Television", "Radio", "Internet", "Film"],
    Options_Korean_Mean: ["영화", "라디오", "인터넷", "컴퓨터"],
    Correct_Answer: "Film",
    Correct_Answer_Korean_Mean: "영화",
  },
  {
    English_Word: "Television",
    Korean_Mean: "텔레비전",
    Options: ["Radio", "Television", "Computer", "Laptop"],
    Options_Korean_Mean: ["라디오", "인터넷", "텔레비전", "노트북"],
    Correct_Answer: "Television",
    Correct_Answer_Korean_Mean: "텔레비전",
  },
  {
    English_Word: "Radio",
    Korean_Mean: "라디오",
    Options: ["Internet", "Computer", "Laptop", "Radio"],
    Options_Korean_Mean: ["인터넷", "컴퓨터", "노트북", "라디오"],
    Correct_Answer: "Radio",
    Correct_Answer_Korean_Mean: "라디오",
  },
  {
    English_Word: "Internet",
    Korean_Mean: "인터넷",
    Options: ["Computer", "Internet", "Tablet", "Phone"],
    Options_Korean_Mean: ["인터넷", "노트북", "태블릿", "전화"],
    Correct_Answer: "Internet",
    Correct_Answer_Korean_Mean: "인터넷",
  },
  {
    English_Word: "Computer",
    Korean_Mean: "컴퓨터",
    Options: ["Computer", "Tablet", "Phone", "Call"],
    Options_Korean_Mean: ["노트북", "태블릿", "컴퓨터", "전화하다"],
    Correct_Answer: "Computer",
    Correct_Answer_Korean_Mean: "컴퓨터",
  },
  {
    English_Word: "Laptop",
    Korean_Mean: "노트북",
    Options: ["Tablet", "Laptop", "Call", "Message"],
    Options_Korean_Mean: ["노트북", "전화", "전화하다", "메시지"],
    Correct_Answer: "Laptop",
    Correct_Answer_Korean_Mean: "노트북",
  },
  {
    English_Word: "Tablet",
    Korean_Mean: "태블릿",
    Options: ["Phone", "Call", "Tablet", "Email"],
    Options_Korean_Mean: ["태블릿", "전화하다", "메시지", "이메일"],
    Correct_Answer: "Tablet",
    Correct_Answer_Korean_Mean: "태블릿",
  },
  {
    English_Word: "Phone",
    Korean_Mean: "전화",
    Options: ["Call", "Message", "Phone", "Chat"],
    Options_Korean_Mean: ["전화", "메시지", "이메일", "채팅"],
    Correct_Answer: "Phone",
    Correct_Answer_Korean_Mean: "전화",
  },
  {
    English_Word: "Call",
    Korean_Mean: "전화하다",
    Options: ["Message", "Email", "Call", "Social media"],
    Options_Korean_Mean: ["메시지", "전화하다", "채팅", "소셜 미디어"],
    Correct_Answer: "Call",
    Correct_Answer_Korean_Mean: "전화하다",
  },
  {
    English_Word: "Message",
    Korean_Mean: "메시지",
    Options: ["Email", "Message", "Social media", "Website"],
    Options_Korean_Mean: ["이메일", "채팅", "소셜 미디어", "메시지"],
    Correct_Answer: "Message",
    Correct_Answer_Korean_Mean: "메시지",
  },
  {
    English_Word: "Email",
    Korean_Mean: "이메일",
    Options: ["Chat", "Social media", "Email", "Blog"],
    Options_Korean_Mean: ["채팅", "소셜 미디어", "이메일", "블로그"],
    Correct_Answer: "Email",
    Correct_Answer_Korean_Mean: "이메일",
  },
  {
    English_Word: "Chat",
    Korean_Mean: "채팅",
    Options: ["Social media", "Website", "Blog", "Chat"],
    Options_Korean_Mean: ["소셜 미디어", "채팅", "블로그", "포스트"],
    Correct_Answer: "Chat",
    Correct_Answer_Korean_Mean: "채팅",
  },
  {
    English_Word: "Social media",
    Korean_Mean: "소셜 미디어",
    Options: ["Website", "Blog", "Social media", "Comment"],
    Options_Korean_Mean: ["웹사이트", "블로그", "소셜 미디어", "댓글"],
    Correct_Answer: "Social media",
    Correct_Answer_Korean_Mean: "소셜 미디어",
  },
  {
    English_Word: "Website",
    Korean_Mean: "웹사이트",
    Options: ["Blog", "Post", "Website", "Like"],
    Options_Korean_Mean: ["웹사이트", "포스트", "댓글", "좋아요"],
    Correct_Answer: "Website",
    Correct_Answer_Korean_Mean: "웹사이트",
  },
  {
    English_Word: "Blog",
    Korean_Mean: "블로그",
    Options: ["Post", "Blog", "Like", "Share"],
    Options_Korean_Mean: ["포스트", "블로그", "좋아요", "공유"],
    Correct_Answer: "Blog",
    Correct_Answer_Korean_Mean: "블로그",
  },
  {
    English_Word: "Post",
    Korean_Mean: "포스트",
    Options: ["Comment", "Like", "Post", "Follow"],
    Options_Korean_Mean: ["포스트", "좋아요", "공유", "팔로우"],
    Correct_Answer: "Post",
    Correct_Answer_Korean_Mean: "포스트",
  },
  {
    English_Word: "Comment",
    Korean_Mean: "댓글",
    Options: ["Like", "Share", "Comment", "Friend"],
    Options_Korean_Mean: ["댓글", "공유", "팔로우", "친구"],
    Correct_Answer: "Comment",
    Correct_Answer_Korean_Mean: "댓글",
  },
  {
    English_Word: "Like",
    Korean_Mean: "좋아요",
    Options: ["Share", "Follow", "Friend", "Like"],
    Options_Korean_Mean: ["공유", "팔로우", "친구", "좋아요"],
    Correct_Answer: "Like",
    Correct_Answer_Korean_Mean: "좋아요",
  },
  {
    English_Word: "Share",
    Korean_Mean: "공유",
    Options: ["Follow", "Friend", "Share", "Trend"],
    Options_Korean_Mean: ["팔로우", "친구", "공유", "트렌드"],
    Correct_Answer: "Share",
    Correct_Answer_Korean_Mean: "공유",
  },
  {
    English_Word: "Follow",
    Korean_Mean: "팔로우",
    Options: ["Friend", "Follow", "Trend", "Viral"],
    Options_Korean_Mean: ["친구", "팔로우", "트렌드", "바이럴"],
    Correct_Answer: "Follow",
    Correct_Answer_Korean_Mean: "팔로우",
  },
  {
    English_Word: "Fitness",
    Korean_Mean: "피트니스",
    Options: ["Exercise", "Fitness", "Game", "Play"],
    Options_Korean_Mean: ["아기", "피트니스", "게임", "놀이"],
    Correct_Answer: "Fitness",
    Correct_Answer_Korean_Mean: "피트니스",
  },
  {
    English_Word: "Friend",
    Korean_Mean: "친구",
    Options: ["Follower", "Trend", "Friend", "Popular"],
    Options_Korean_Mean: ["친구", "트렌드", "바이럴", "인기 있는"],
    Correct_Answer: "Friend",
    Correct_Answer_Korean_Mean: "친구",
  },
  {
    English_Word: "Follower",
    Korean_Mean: "팔로워",
    Options: ["Follower", "Viral", "Popular", "Trending"],
    Options_Korean_Mean: ["트렌드", "팔로워", "인기 있는", "트렌드 중인"],
    Correct_Answer: "Follower",
    Correct_Answer_Korean_Mean: "팔로워",
  },
  {
    English_Word: "Trend",
    Korean_Mean: "트렌드",
    Options: ["Viral", "Popular", "Trend", "News"],
    Options_Korean_Mean: ["바이럴", "인기 있는", "트렌드", "뉴스"],
    Correct_Answer: "Trend",
    Correct_Answer_Korean_Mean: "트렌드",
  },
];
