export const oxDay8 = [
  {
    English_Word: "Team",
    Korean_Mean: "팀",
    Options: ["Group", "Organization", "Team", "Company"],
    Options_Korean_Mean: ["그룹", "조직", "팀", "기업"],
    Correct_Answer: "Team",
    Correct_Answer_Korean_Mean: "팀",
  },
  {
    English_Word: "Organization",
    Korean_Mean: "조직",
    Options: ["Team", "Company", "Group", "Organization"],
    Options_Korean_Mean: ["팀", "기업", "단체", "조직"],
    Correct_Answer: "Organization",
    Correct_Answer_Korean_Mean: "조직",
  },
  {
    English_Word: "Company",
    Korean_Mean: "기업",
    Options: ["Group", "Company", "Organization", "Business"],
    Options_Korean_Mean: ["단체", "기업", "그룹", "비즈니스"],
    Correct_Answer: "Company",
    Correct_Answer_Korean_Mean: "기업",
  },
  {
    English_Word: "Business",
    Korean_Mean: "비즈니스",
    Options: ["Market", "Enterprise", "Management", "Business"],
    Options_Korean_Mean: ["시장", "사업", "경영", "비즈니스"],
    Correct_Answer: "Business",
    Correct_Answer_Korean_Mean: "비즈니스",
  },
  {
    English_Word: "Market",
    Korean_Mean: "시장",
    Options: ["Customer", "Market", "Consumer", "Product"],
    Options_Korean_Mean: ["고객", "시장", "소비자", "생산물"],
    Correct_Answer: "Market",
    Correct_Answer_Korean_Mean: "시장",
  },
  {
    English_Word: "Customer",
    Korean_Mean: "고객",
    Options: ["User", "Consumer", "Customer", "Client"],
    Options_Korean_Mean: ["사용자", "소비자", "고객", "클라이언트"],
    Correct_Answer: "Customer",
    Correct_Answer_Korean_Mean: "고객",
  },
  {
    English_Word: "Client",
    Korean_Mean: "의뢰인",
    Options: ["Client", "Consumer", "Customer", "User"],
    Options_Korean_Mean: ["클라이언트", "소비자", "고객", "사용자"],
    Correct_Answer: "Client",
    Correct_Answer_Korean_Mean: "의뢰인",
  },
  {
    English_Word: "Consumer",
    Korean_Mean: "소비자",
    Options: ["User", "Consumer", "Customer", "Client"],
    Options_Korean_Mean: ["사용자", "소비자", "고객", "클라이언트"],
    Correct_Answer: "Consumer",
    Correct_Answer_Korean_Mean: "소비자",
  },
  {
    English_Word: "Product",
    Korean_Mean: "생산물",
    Options: ["Product", "Goods", "Artifact", "Apple"],
    Options_Korean_Mean: ["제품", "상품", "제작물", "생산물"],
    Correct_Answer: "Product",
    Correct_Answer_Korean_Mean: "생산물",
  },
  {
    English_Word: "Service",
    Korean_Mean: "서비스",
    Options: ["Service", "Support", "Assistance", "Help"],
    Options_Korean_Mean: ["서비스", "지원", "보조", "도움"],
    Correct_Answer: "Service",
    Correct_Answer_Korean_Mean: "서비스",
  },
  {
    English_Word: "Quality",
    Korean_Mean: "품질",
    Options: ["Level", "Standard", "Quality", "Grade"],
    Options_Korean_Mean: ["수준", "표준", "품질", "등급"],
    Correct_Answer: "Quality",
    Correct_Answer_Korean_Mean: "품질",
  },
  {
    English_Word: "Quantity",
    Korean_Mean: "수량",
    Options: ["Number", "Amount", "Quantity", "Volume"],
    Options_Korean_Mean: ["숫자", "양", "수량", "용량"],
    Correct_Answer: "Quantity",
    Correct_Answer_Korean_Mean: "수량",
  },
  {
    English_Word: "Price",
    Korean_Mean: "가격",
    Options: ["Cost", "Rate", "Price", "Value"],
    Options_Korean_Mean: ["비용", "비율", "가격", "가치"],
    Correct_Answer: "Price",
    Correct_Answer_Korean_Mean: "가격",
  },
  {
    English_Word: "Cost",
    Korean_Mean: "비용",
    Options: ["Value", "Expense", "Cost", "Budget"],
    Options_Korean_Mean: ["가치", "지출", "비용", "예산"],
    Correct_Answer: "Cost",
    Correct_Answer_Korean_Mean: "비용",
  },
  {
    English_Word: "Budget",
    Korean_Mean: "예산",
    Options: ["Expense", "Budget", "Income", "Savings"],
    Options_Korean_Mean: ["지출", "예산", "수입", "저축"],
    Correct_Answer: "Budget",
    Correct_Answer_Korean_Mean: "예산",
  },
  {
    English_Word: "Expense",
    Korean_Mean: "경비",
    Options: ["Savings", "Expenditure", "Expense", "Cost"],
    Options_Korean_Mean: ["저축", "지출", "경비", "비용"],
    Correct_Answer: "Expense",
    Correct_Answer_Korean_Mean: "경비",
  },
  {
    English_Word: "Profit",
    Korean_Mean: "이익",
    Options: ["Gain", "Profit", "Revenue", "Income"],
    Options_Korean_Mean: ["이익", "수익", "수입", "소득"],
    Correct_Answer: "Profit",
    Correct_Answer_Korean_Mean: "이익",
  },
  {
    English_Word: "Loss",
    Korean_Mean: "손실",
    Options: ["Loss", "Deficit", "Decrease", "Reduction"],
    Options_Korean_Mean: ["손실", "적자", "코인", "핵심"],
    Correct_Answer: "Loss",
    Correct_Answer_Korean_Mean: "손실",
  },
  {
    English_Word: "Investment",
    Korean_Mean: "투자",
    Options: ["Investment", "Capital", "Expenditure", "Funding"],
    Options_Korean_Mean: ["투자", "자본", "지출", "자금"],
    Correct_Answer: "Investment",
    Correct_Answer_Korean_Mean: "투자",
  },
  {
    English_Word: "Return",
    Korean_Mean: "수익",
    Options: ["Earnings", "Return", "Profit", "Income"],
    Options_Korean_Mean: ["수익", "저장", "주식", "소득"],
    Correct_Answer: "Return",
    Correct_Answer_Korean_Mean: "수익",
  },
  {
    English_Word: "Growth",
    Korean_Mean: "성장",
    Options: ["Advancement", "Development", "Growth", "Progress"],
    Options_Korean_Mean: ["진보", "개발", "성장", "진전"],
    Correct_Answer: "Growth",
    Correct_Answer_Korean_Mean: "성장",
  },
  {
    English_Word: "Development",
    Korean_Mean: "개발",
    Options: ["Improvement", "Progress", "Development", "Growth"],
    Options_Korean_Mean: ["개선", "진전", "개발", "성장"],
    Correct_Answer: "Development",
    Correct_Answer_Korean_Mean: "개발",
  },
  {
    English_Word: "Progress",
    Korean_Mean: "진전",
    Options: ["Progress", "Advancement", "Growth", "Development"],
    Options_Korean_Mean: ["진전", "진보", "성장", "개발"],
    Correct_Answer: "Progress",
    Correct_Answer_Korean_Mean: "진전",
  },
  {
    English_Word: "Improvement",
    Korean_Mean: "개선",
    Options: ["Change", "Progress", "Development", "Improvement"],
    Options_Korean_Mean: ["변화", "진전", "개발", "개선"],
    Correct_Answer: "Improvement",
    Correct_Answer_Korean_Mean: "개선",
  },
  {
    English_Word: "Change",
    Korean_Mean: "변화",
    Options: ["Stability", "Balance", "Change", "Harmony"],
    Options_Korean_Mean: ["안정성", "균형", "변화", "협력"],
    Correct_Answer: "Change",
    Correct_Answer_Korean_Mean: "변화",
  },
  {
    English_Word: "Stability",
    Korean_Mean: "안정성",
    Options: ["Change", "Stability", "Balance", "Harmony"],
    Options_Korean_Mean: ["변화", "안정성", "균형", "협력"],
    Correct_Answer: "Stability",
    Correct_Answer_Korean_Mean: "안정성",
  },
  {
    English_Word: "Balance",
    Korean_Mean: "균형",
    Options: ["Harmony", "Change", "Stability", "Balance"],
    Options_Korean_Mean: ["협력", "변화", "안정성", "균형"],
    Correct_Answer: "Balance",
    Correct_Answer_Korean_Mean: "균형",
  },
  {
    English_Word: "Harmony",
    Korean_Mean: "협력",
    Options: ["Balance", "Change", "Stability", "Harmony"],
    Options_Korean_Mean: ["균형", "변화", "안정성", "협력"],
    Correct_Answer: "Harmony",
    Correct_Answer_Korean_Mean: "협력",
  },
  {
    English_Word: "Conflict",
    Korean_Mean: "충돌",
    Options: ["Resolution", "Conflict", "Agreement", "Disagreement"],
    Options_Korean_Mean: ["해결", "충돌", "합의", "불일치"],
    Correct_Answer: "Conflict",
    Correct_Answer_Korean_Mean: "충돌",
  },
  {
    English_Word: "Resolution",
    Korean_Mean: "해결",
    Options: ["Disagreement", "Resolution", "Agreement", "Negotiation"],
    Options_Korean_Mean: ["불일치", "해결", "합의", "협상"],
    Correct_Answer: "Resolution",
    Correct_Answer_Korean_Mean: "해결",
  },
  {
    English_Word: "Agreement",
    Korean_Mean: "합의",
    Options: ["Negotiation", "Agreement", "Disagreement", "Compromise"],
    Options_Korean_Mean: ["협상", "합의", "불일치", "타협"],
    Correct_Answer: "Agreement",
    Correct_Answer_Korean_Mean: "합의",
  },
  {
    English_Word: "Disagreement",
    Korean_Mean: "불일치",
    Options: ["Compromise", "Agreement", "Disagreement", "Negotiation"],
    Options_Korean_Mean: ["타협", "합의", "불일치", "협상"],
    Correct_Answer: "Disagreement",
    Correct_Answer_Korean_Mean: "불일치",
  },
  {
    English_Word: "Argument",
    Korean_Mean: "논쟁",
    Options: ["Debate", "Negotiation", "Agreement", "Argument"],
    Options_Korean_Mean: ["토론", "협상", "합의", "논쟁"],
    Correct_Answer: "Argument",
    Correct_Answer_Korean_Mean: "논쟁",
  },
  {
    English_Word: "Debate",
    Korean_Mean: "토론",
    Options: ["Agreement", "Debate", "Negotiation", "Compromise"],
    Options_Korean_Mean: ["합의", "토론", "협상", "타협"],
    Correct_Answer: "Debate",
    Correct_Answer_Korean_Mean: "토론",
  },
  {
    English_Word: "Negotiation",
    Korean_Mean: "협상",
    Options: ["Compromise", "Negotiation", "Agreement", "Debate"],
    Options_Korean_Mean: ["타협", "협상", "합의", "토론"],
    Correct_Answer: "Negotiation",
    Correct_Answer_Korean_Mean: "협상",
  },
  {
    English_Word: "Compromise",
    Korean_Mean: "타협",
    Options: ["Collaboration", "Compromise", "Conflict", "Resolution"],
    Options_Korean_Mean: ["협력", "타협", "충돌", "해결"],
    Correct_Answer: "Compromise",
    Correct_Answer_Korean_Mean: "타협",
  },
  {
    English_Word: "Collaboration",
    Korean_Mean: "협력",
    Options: ["Cooperation", "Collaboration", "Competition", "Conflict"],
    Options_Korean_Mean: ["협조", "협력", "경쟁", "충돌"],
    Correct_Answer: "Collaboration",
    Correct_Answer_Korean_Mean: "협력",
  },
  {
    English_Word: "Cooperation",
    Korean_Mean: "협조",
    Options: ["Competition", "Cooperation", "Collaboration", "Conflict"],
    Options_Korean_Mean: ["경쟁", "협조", "협력", "충돌"],
    Correct_Answer: "Cooperation",
    Correct_Answer_Korean_Mean: "협조",
  },
  {
    English_Word: "Competition",
    Korean_Mean: "경쟁",
    Options: ["Success", "Failure", "Competition", "Achievement"],
    Options_Korean_Mean: ["성공", "실패", "경쟁", "성취"],
    Correct_Answer: "Competition",
    Correct_Answer_Korean_Mean: "경쟁",
  },
  {
    English_Word: "Success",
    Korean_Mean: "성공",
    Options: ["Failure", "Achievement", "Success", "Competition"],
    Options_Korean_Mean: ["실패", "성취", "성공", "경쟁"],
    Correct_Answer: "Success",
    Correct_Answer_Korean_Mean: "성공",
  },
  {
    English_Word: "Failure",
    Korean_Mean: "실패",
    Options: ["Failure", "Success", "Achievement", "Goal"],
    Options_Korean_Mean: ["실패", "성공", "성취", "목표"],
    Correct_Answer: "Failure",
    Correct_Answer_Korean_Mean: "실패",
  },
  {
    English_Word: "Achievement",
    Korean_Mean: "성취",
    Options: ["Goal", "Dream", "Vision", "Achievement"],
    Options_Korean_Mean: ["목표", "꿈", "비전", "성취"],
    Correct_Answer: "Achievement",
    Correct_Answer_Korean_Mean: "성취",
  },
  {
    English_Word: "Goal",
    Korean_Mean: "목표",
    Options: ["Dream", "Vision", "Mission", "Goal"],
    Options_Korean_Mean: ["꿈", "비전", "미션", "목표"],
    Correct_Answer: "Goal",
    Correct_Answer_Korean_Mean: "목표",
  },
  {
    English_Word: "Dream",
    Korean_Mean: "꿈",
    Options: ["Purpose", "Passion", "Dream", "Vision"],
    Options_Korean_Mean: ["목적", "열정", "꿈", "비전"],
    Correct_Answer: "Dream",
    Correct_Answer_Korean_Mean: "꿈",
  },
  {
    English_Word: "Vision",
    Korean_Mean: "비전",
    Options: ["Mission", "Purpose", "Vision", "Passion"],
    Options_Korean_Mean: ["미션", "목적", "비전", "열정"],
    Correct_Answer: "Vision",
    Correct_Answer_Korean_Mean: "비전",
  },
  {
    English_Word: "Mission",
    Korean_Mean: "미션",
    Options: ["Purpose", "Mission", "Passion", "Vision"],
    Options_Korean_Mean: ["목적", "미션", "열정", "비전"],
    Correct_Answer: "Mission",
    Correct_Answer_Korean_Mean: "미션",
  },
  {
    English_Word: "Purpose",
    Korean_Mean: "목적",
    Options: ["Passion", "Purpose", "Mission", "Vision"],
    Options_Korean_Mean: ["열정", "목적", "미션", "비전"],
    Correct_Answer: "Purpose",
    Correct_Answer_Korean_Mean: "목적",
  },
  {
    English_Word: "Passion",
    Korean_Mean: "열정",
    Options: ["Purpose", "Passion", "Mission", "Vision"],
    Options_Korean_Mean: ["목적", "열정", "미션", "비전"],
    Correct_Answer: "Passion",
    Correct_Answer_Korean_Mean: "열정",
  },
  {
    English_Word: "Motivation",
    Korean_Mean: "동기부여",
    Options: ["Motivation", "Passion", "Purpose", "Vision"],
    Options_Korean_Mean: ["동기부여", "열정", "목적", "비전"],
    Correct_Answer: "Motivation",
    Correct_Answer_Korean_Mean: "동기부여",
  },
];
