export const oxDay9 = [
  {
    English_Word: "Tactic",
    Korean_Mean: "전술",
    Options: ["Strategy", "Tactic", "Plan", "Approach"],
    Options_Korean_Mean: ["전략", "전술", "계획", "접근"],
    Correct_Answer: "Tactic",
    Correct_Answer_Korean_Mean: "전술",
  },
  {
    English_Word: "Action",
    Korean_Mean: "행동",
    Options: ["Deed", "Activity", "Action", "Behavior"],
    Options_Korean_Mean: ["행위", "활동", "행동", "행동양식"],
    Correct_Answer: "Action",
    Correct_Answer_Korean_Mean: "행동",
  },
  {
    English_Word: "Reaction",
    Korean_Mean: "반응",
    Options: ["Response", "Reaction", "Feedback", "Counteraction"],
    Options_Korean_Mean: ["응답", "반응", "피드백", "반작용"],
    Correct_Answer: "Reaction",
    Correct_Answer_Korean_Mean: "반응",
  },
  {
    English_Word: "Decision",
    Korean_Mean: "결정",
    Options: ["Choice", "Decision", "Selection", "Determination"],
    Options_Korean_Mean: ["선택", "결정", "선정", "결심"],
    Correct_Answer: "Decision",
    Correct_Answer_Korean_Mean: "결정",
  },
  {
    English_Word: "Choice",
    Korean_Mean: "선택",
    Options: ["Decision", "Preference", "Choice", "Option"],
    Options_Korean_Mean: ["결정", "선호", "선택", "옵션"],
    Correct_Answer: "Choice",
    Correct_Answer_Korean_Mean: "선택",
  },
  {
    English_Word: "Option",
    Korean_Mean: "옵션",
    Options: ["Alternative", "Option", "Choice", "Variety"],
    Options_Korean_Mean: ["대안", "옵션", "선택", "다양성"],
    Correct_Answer: "Option",
    Correct_Answer_Korean_Mean: "옵션",
  },
  {
    English_Word: "Solution",
    Korean_Mean: "해결책",
    Options: ["Resolution", "Answer", "Solution", "Conclusion"],
    Options_Korean_Mean: ["해결", "답변", "해결책", "결론"],
    Correct_Answer: "Solution",
    Correct_Answer_Korean_Mean: "해결책",
  },
  {
    English_Word: "Problem",
    Korean_Mean: "문제",
    Options: ["Challenge", "Obstacle", "Problem", "Issue"],
    Options_Korean_Mean: ["도전", "장애물", "문제", "이슈"],
    Correct_Answer: "Problem",
    Correct_Answer_Korean_Mean: "문제",
  },
  {
    English_Word: "Challenge",
    Korean_Mean: "도전",
    Options: ["Difficulty", "Challenge", "Obstacle", "Trial"],
    Options_Korean_Mean: ["어려움", "도전", "장애물", "시험"],
    Correct_Answer: "Challenge",
    Correct_Answer_Korean_Mean: "도전",
  },
  {
    English_Word: "Difficulty",
    Korean_Mean: "어려움",
    Options: ["Obstacle", "Difficulty", "Challenge", "Hardship"],
    Options_Korean_Mean: ["장애물", "어려움", "도전", "고난"],
    Correct_Answer: "Difficulty",
    Correct_Answer_Korean_Mean: "어려움",
  },
  {
    English_Word: "Obstacle",
    Korean_Mean: "장애물",
    Options: ["Challenge", "Barrier", "Obstacle", "Hurdle"],
    Options_Korean_Mean: ["도전", "장벽", "장애물", "장애"],
    Correct_Answer: "Obstacle",
    Correct_Answer_Korean_Mean: "장애물",
  },
  {
    English_Word: "Opportunity",
    Korean_Mean: "기회",
    Options: ["Chance", "Opportunity", "Prospect", "Possibility"],
    Options_Korean_Mean: ["기회", "만남", "전망", "가능성"],
    Correct_Answer: "Opportunity",
    Correct_Answer_Korean_Mean: "기회",
  },
  {
    English_Word: "Risk",
    Korean_Mean: "위험",
    Options: ["Danger", "Risk", "Hazard", "Threat"],
    Options_Korean_Mean: ["위험", "핵", "라면", "전수"],
    Correct_Answer: "Risk",
    Correct_Answer_Korean_Mean: "위험",
  },
  {
    English_Word: "Reward",
    Korean_Mean: "보상",
    Options: ["Compensation", "Award", "Reward", "Prize"],
    Options_Korean_Mean: ["보상", "상", "그림", "궁"],
    Correct_Answer: "Reward",
    Correct_Answer_Korean_Mean: "보상",
  },
  {
    English_Word: "Benefit",
    Korean_Mean: "이익",
    Options: ["Advantage", "Profit", "Benefit", "Gain"],
    Options_Korean_Mean: ["장점", "이익", "만세", "조리"],
    Correct_Answer: "Benefit",
    Correct_Answer_Korean_Mean: "이익",
  },
  {
    English_Word: "Advantage",
    Korean_Mean: "장점",
    Options: ["Benefit", "Advantage", "Merit", "Strength"],
    Options_Korean_Mean: ["이익", "장점", "억압", "강점"],
    Correct_Answer: "Advantage",
    Correct_Answer_Korean_Mean: "장점",
  },
  {
    English_Word: "Disadvantage",
    Korean_Mean: "단점",
    Options: ["Weakness", "Flaw", "Disadvantage", "Limitation"],
    Options_Korean_Mean: ["약점", "결함", "단점", "제한"],
    Correct_Answer: "Disadvantage",
    Correct_Answer_Korean_Mean: "단점",
  },
  {
    English_Word: "Consequence",
    Korean_Mean: "결과",
    Options: ["Outcome", "Effect", "Consequence", "Result"],
    Options_Korean_Mean: ["결과", "효과", "천수", "노랑"],
    Correct_Answer: "Consequence",
    Correct_Answer_Korean_Mean: "결과",
  },
  {
    English_Word: "Result",
    Korean_Mean: "결과",
    Options: ["Conclusion", "Result", "Output", "Findings"],
    Options_Korean_Mean: ["결론", "결과", "산출물", "조사"],
    Correct_Answer: "Result",
    Correct_Answer_Korean_Mean: "결과",
  },
  {
    English_Word: "Outcome",
    Korean_Mean: "성과",
    Options: ["Output", "Outcome", "Result", "Product"],
    Options_Korean_Mean: ["산출물", "성과", "보라", "제품"],
    Correct_Answer: "Outcome",
    Correct_Answer_Korean_Mean: "성과",
  },
  {
    English_Word: "Effect",
    Korean_Mean: "효과",
    Options: ["Impact", "Effect", "Influence", "Consequence"],
    Options_Korean_Mean: ["영향", "효과", "마차", "결과"],
    Correct_Answer: "Effect",
    Correct_Answer_Korean_Mean: "효과",
  },
  {
    English_Word: "Cause",
    Korean_Mean: "원인",
    Options: ["Reason", "Cause", "Source", "Origin"],
    Options_Korean_Mean: ["이유", "원인", "출처", "기원"],
    Correct_Answer: "Cause",
    Correct_Answer_Korean_Mean: "원인",
  },
  {
    English_Word: "Reason",
    Korean_Mean: "이유",
    Options: ["Explanation", "Reason", "Justification", "Logic"],
    Options_Korean_Mean: ["설명", "이유", "정당화", "논리"],
    Correct_Answer: "Reason",
    Correct_Answer_Korean_Mean: "이유",
  },
  {
    English_Word: "Purpose",
    Korean_Mean: "목적",
    Options: ["Goal", "Objective", "Purpose", "Intention"],
    Options_Korean_Mean: ["목표", "목적", "태연", "의도"],
    Correct_Answer: "Purpose",
    Correct_Answer_Korean_Mean: "목적",
  },
  {
    English_Word: "Meaning",
    Korean_Mean: "의미",
    Options: ["Significance", "Meaning", "Sense", "Importance"],
    Options_Korean_Mean: ["중요성", "의미", "감각", "비상"],
    Correct_Answer: "Meaning",
    Correct_Answer_Korean_Mean: "의미",
  },
  {
    English_Word: "Value",
    Korean_Mean: "가치",
    Options: ["Worth", "Value", "Merit", "Importance"],
    Options_Korean_Mean: ["가치", "가림", "장점", "중요성"],
    Correct_Answer: "Value",
    Correct_Answer_Korean_Mean: "가치",
  },
  {
    English_Word: "Belief",
    Korean_Mean: "신념",
    Options: ["Faith", "Belief", "Conviction", "Trust"],
    Options_Korean_Mean: ["신앙", "신념", "확신", "신뢰"],
    Correct_Answer: "Belief",
    Correct_Answer_Korean_Mean: "신념",
  },
  {
    English_Word: "Faith",
    Korean_Mean: "신앙",
    Options: ["Devotion", "Faith", "Reliance", "Trust"],
    Options_Korean_Mean: ["헌신", "신앙", "의존", "신뢰"],
    Correct_Answer: "Faith",
    Correct_Answer_Korean_Mean: "신앙",
  },
  {
    English_Word: "Religion",
    Korean_Mean: "종교",
    Options: ["Spirituality", "Religion", "Faith", "Belief"],
    Options_Korean_Mean: ["영성", "종교", "신앙", "신념"],
    Correct_Answer: "Religion",
    Correct_Answer_Korean_Mean: "종교",
  },
  {
    English_Word: "Spirituality",
    Korean_Mean: "영성",
    Options: ["Religion", "Spirituality", "Mysticism", "Sacredness"],
    Options_Korean_Mean: ["종교", "영성", "신비주의", "신성"],
    Correct_Answer: "Spirituality",
    Correct_Answer_Korean_Mean: "영성",
  },
  {
    English_Word: "God",
    Korean_Mean: "신",
    Options: ["Deity", "God", "Divinity", "Supreme Being"],
    Options_Korean_Mean: ["신", "무", "신성", "최고의 존재"],
    Correct_Answer: "God",
    Correct_Answer_Korean_Mean: "신",
  },
  {
    English_Word: "Faithful",
    Korean_Mean: "신앙심 있는",
    Options: ["Devoted", "Faithful", "Loyal", "Dedicated"],
    Options_Korean_Mean: ["헌신적인", "신앙심 있는", "충성스러운", "전념한"],
    Correct_Answer: "Faithful",
    Correct_Answer_Korean_Mean: "신앙심 있는",
  },
  {
    English_Word: "Atheist",
    Korean_Mean: "무신론자",
    Options: ["Atheist", "Agnostic", "Theist", "Believer"],
    Options_Korean_Mean: ["무신론자", "무지신론자", "신자", "신앙자"],
    Correct_Answer: "Atheist",
    Correct_Answer_Korean_Mean: "무신론자",
  },
  {
    English_Word: "Agnostic",
    Korean_Mean: "무지신론자",
    Options: ["Agnostic", "Atheist", "Theist", "Believer"],
    Options_Korean_Mean: ["무지신론자", "무신론자", "신자", "신앙자"],
    Correct_Answer: "Agnostic",
    Correct_Answer_Korean_Mean: "무지신론자",
  },
  {
    English_Word: "Science",
    Korean_Mean: "과학",
    Options: ["Biology", "Physics", "Chemistry", "Science"],
    Options_Korean_Mean: ["생물학", "물리학", "화학", "과학"],
    Correct_Answer: "Science",
    Correct_Answer_Korean_Mean: "과학",
  },
  {
    English_Word: "Scientist",
    Korean_Mean: "과학자",
    Options: ["Researcher", "Scientist", "Explorer", "Inventor"],
    Options_Korean_Mean: ["연구자", "과학자", "탐험가", "발명가"],
    Correct_Answer: "Scientist",
    Correct_Answer_Korean_Mean: "과학자",
  },
  {
    English_Word: "Research",
    Korean_Mean: "연구",
    Options: ["Study", "Investigation", "Research", "Analysis"],
    Options_Korean_Mean: ["공부", "조사", "연구", "분석"],
    Correct_Answer: "Research",
    Correct_Answer_Korean_Mean: "연구",
  },
  {
    English_Word: "Discovery",
    Korean_Mean: "발견",
    Options: ["Exploration", "Discovery", "Invention", "Unveiling"],
    Options_Korean_Mean: ["탐험", "발견", "발명", "발표"],
    Correct_Answer: "Discovery",
    Correct_Answer_Korean_Mean: "발견",
  },
  {
    English_Word: "Experiment",
    Korean_Mean: "실험",
    Options: ["Experiment", "Trial", "Test", "Procedure"],
    Options_Korean_Mean: ["실험", "시험", "테스트", "절차"],
    Correct_Answer: "Experiment",
    Correct_Answer_Korean_Mean: "실험",
  },
  {
    English_Word: "Observation",
    Korean_Mean: "관찰",
    Options: ["Inspection", "Observation", "Examination", "Survey"],
    Options_Korean_Mean: ["검사", "관찰", "조사", "설문"],
    Correct_Answer: "Observation",
    Correct_Answer_Korean_Mean: "관찰",
  },
  {
    English_Word: "Hypothesis",
    Korean_Mean: "가설",
    Options: ["Assumption", "Hypothesis", "Theory", "Conjecture"],
    Options_Korean_Mean: ["가정", "가설", "이론", "추측"],
    Correct_Answer: "Hypothesis",
    Correct_Answer_Korean_Mean: "가설",
  },
  {
    English_Word: "Theory",
    Korean_Mean: "이론",
    Options: ["Principle", "Theory", "Concept", "Doctrine"],
    Options_Korean_Mean: ["원리", "이론", "개념", "교리"],
    Correct_Answer: "Theory",
    Correct_Answer_Korean_Mean: "이론",
  },
  {
    English_Word: "Law",
    Korean_Mean: "법칙",
    Options: ["Regulation", "Law", "Rule", "Statute"],
    Options_Korean_Mean: ["규정", "법", "규칙", "법규"],
    Correct_Answer: "Law",
    Correct_Answer_Korean_Mean: "법칙",
  },
  {
    English_Word: "Principle",
    Korean_Mean: "원리",
    Options: ["Doctrine", "Principle", "Fundamental", "Essence"],
    Options_Korean_Mean: ["교리", "원리", "근본적인", "본질"],
    Correct_Answer: "Principle",
    Correct_Answer_Korean_Mean: "원리",
  },
  {
    English_Word: "Philosophy",
    Korean_Mean: "철학",
    Options: ["Philosophy", "Ideology", "Belief System", "Worldview"],
    Options_Korean_Mean: ["철학", "이념", "신념 체계", "세계관"],
    Correct_Answer: "Philosophy",
    Correct_Answer_Korean_Mean: "철학",
  },
  {
    English_Word: "Logic",
    Korean_Mean: "논리",
    Options: ["Reasoning", "Logic", "Rationality", "Argumentation"],
    Options_Korean_Mean: ["추론", "논리", "합리성", "논쟁"],
    Correct_Answer: "Logic",
    Correct_Answer_Korean_Mean: "논리",
  },
  {
    English_Word: "Reasoning",
    Korean_Mean: "추론",
    Options: ["Inference", "Reasoning", "Deduction", "Induction"],
    Options_Korean_Mean: ["추론", "논리", "연역", "귀납"],
    Correct_Answer: "Reasoning",
    Correct_Answer_Korean_Mean: "추론",
  },
  {
    English_Word: "Rational",
    Korean_Mean: "합리적인",
    Options: ["Logical", "Rational", "Reasonable", "Sensible"],
    Options_Korean_Mean: ["논리적인", "합리적인", "부자연", "분별력 있는"],
    Correct_Answer: "Rational",
    Correct_Answer_Korean_Mean: "합리적인",
  },
  {
    English_Word: "Irrational",
    Korean_Mean: "비합리적인",
    Options: ["Unreasonable", "Illogical", "Irrational", "Absurd"],
    Options_Korean_Mean: [
      "합리적이지 않은",
      "논리에 어긋나는",
      "비합리적인",
      "터무니 없는",
    ],
    Correct_Answer: "Irrational",
    Correct_Answer_Korean_Mean: "비합리적인",
  },
];
